### DISCUSSION TITLE
Perform actions on multiple entities with one card

### DISCUSSION THREAD

**Discussion by caraar12345** [piitaya/lovelace-mushroom#1226] [Q&A] [answered]
Hey folks,

I was wondering if it's possible to use two different entities for actions within the same card?

So for example, the below card:

<img width="269" alt="Mushroom template card with two lines showing temperature and humidity within the same card" src="https://github.com/piitaya/lovelace-mushroom/assets/6129428/8f6b9a2f-24a6-408d-8f28-412dbcea0781">

I'd like to be able to tap it to bring up the temperature more info dialog, but tap and hold to bring up the humidity more info dialog.

Any ideas would be greatly appreciated!

Cheers :)

**Comment by DarkInspiration** [comment]
@caraar12345 Did you ever figure this one out, I am facing the same issue.

**Comment by piitaya** [comment, marked as answer]
You can do this using `yaml`. It's not a Mushroom feature but a built-in feature for every card.

```yaml
tap_action:
  action: more-info
  entity: sensor.temperature
hold_action:
  action: more-info
  entity: sensor.humidity
  ```

Note, if you don't set `entity`, it will the entity selected in your card.
