### DISCUSSION TITLE
Declaring variables once in the template-card

### DISCUSSION THREAD

**Discussion by Netesfiu** [piitaya/lovelace-mushroom#1294] [Ideas]
Hello!

I make use of template cards all the time and i'm wondering if it would be possible to declare variables only once for the whole card.

Most of my cards' color, icon, primary, secondary etc. is checking similar variables and would be more efficient to just declare those variables once and use them troughout the template.

Ex: i have this card:
```yaml
type: custom:mushroom-template-card
primary: >-
  {% set export = {
      "start": states('input_number.export_start')|float,
      "current": states('sensor.w1000_export')|float 
  } %}

  {% set import = {
      "start": states('input_number.import_start')|float,
      "current": states('sensor.w1000_import')|float 
  } %}

  {% set dev = (export.current - export.start)-(import.current - import.start)%}

  Villanyóra Különbözet: {%if dev > 0 %} + {{dev|abs|round(3)}} {% else %} -
  {{dev|abs|round(3)}} {%endif%} kWh
secondary: |-
  {% set export = {
      "start": states('input_number.export_start')|float,
      "current": states('sensor.w1000_export')|float 
  } %}
  {% set import = {
      "start": states('input_number.import_start')|float,
      "current": states('sensor.w1000_import')|float 
  } %}
  {% set dev = (export.current - export.start)-(import.current - import.start)%}
  import: {{states('sensor.w1000_import')}} kWh
  export: {{states('sensor.w1000_export')}} kWh
icon: mdi:meter-electric-outline
icon_color: orange
multiline_secondary: true
tap_action:
  action: navigate
  navigation_path: /lovelace/energia
view_layout:
  grid-area: sidebar3
```

and maybe i could do this instead:
```yaml
type: custom:mushroom-template-card
variables:
 - export:
   start: "{{states('input_number.export_start')|float}}"
   current: "{{states('sensor.w1000_export')|float}}"
 - import:
   start: "{{states('input_number.import_start')|float}}"
   current: "{{states('input_number.import_current')|float}}"
 - dev: "{{(export.current - export.start)-(import.current - import.start)}}"
primary: >-
  Villanyóra Különbözet: {%if dev > 0 %} + {{dev|abs|round(3)}} {% else %} -
  {{dev|abs|round(3)}} {%endif%} kWh
secondary: |-
  import: {{import.current)}} kWh
  export: {{export.current)}} kWh
icon: mdi:meter-electric-outline
icon_color: orange
multiline_secondary: true
tap_action:
  action: navigate
  navigation_path: /lovelace/energia
view_layout:
  grid-area: sidebar3
```

I hope I'm not the one who did not find solution for this
