### DISCUSSION TITLE
Mushroom Fan Card - Low, Medium & High Settings vs 100% Slider

### DISCUSSION THREAD

**Discussion by paterson37** [piitaya/lovelace-mushroom#1372] [Q&A]
Hi folks,

Is there anyone more knowledgable than me that knows if we can make this card select low, medium, high options rather than just the percentage slider?

Cheers!

**Comment by backyardaussie** [comment]
Looking for the same info

Until buttons can be added to the fan instead of a slider this is my work around
<img width="412" height="82" alt="Screenshot 2026-09-19 at 9 30 45 pm" src="https://github.com/user-attachments/assets/ab9def59-3134-442e-8650-665330c18595" />

```
type: custom:stack-in-card
cards:
  - type: grid
    columns: 2
    square: false
    cards:
      - type: custom:mushroom-fan-card
        entity: fan.master_bedroom_fan
        name: Master bedroom Fan
        secondary_info: none
        card_mod:
          style:
            style: |
              ha-card {
                border-width: 0px;
              }
      - type: custom:paper-buttons-row
        preset: mushroom
        styles:
          justify-content: flex-end
        base_config:
          styles:
            button:
              margin-top: 6px
              margin-right: 16px
        buttons:
          - layout: icon
            icon: mdi:fan-speed-1
            styles:
              button:
                color: |-
                  {% if is_state('fan.master_bedroom_fan', 'on') and
                  state_attr('fan.master_bedroom_fan', 'percentage') == 16 %}
                    var(--primary-color)
                  {% else %}
                    grey
                  {% endif %}
            tap_action:
              action: call-service
              service: fan.set_percentage
              service_data:
                entity_id: fan.master_bedroom_fan
                percentage: 16
          - layout: icon
            icon: mdi:fan-speed-2
            styles:
              button:
                color: |-
                  {% if is_state('fan.master_bedroom_fan', 'on') and
                  state_attr('fan.master_bedroom_fan', 'percentage') == 50 %}
                    var(--primary-color)
                  {% else %}
                    grey
                  {% endif %}
            tap_action:
              action: call-service
              service: fan.set_percentage
              service_data:
                entity_id: fan.master_bedroom_fan
                percentage: 50
          - layout: icon
            icon: mdi:fan-speed-3
            styles:
              button:
                color: |-
                  {% if is_state('fan.master_bedroom_fan', 'on') and
                  state_attr('fan.master_bedroom_fan', 'percentage') == 100 %}
                    var(--primary-color)
                  {% else %}
                    grey
                  {% endif %}
            tap_action:
              action: call-service
              service: fan.set_percentage
              service_data:
                entity_id: fan.master_bedroom_fan
                percentage: 100


```
