### DISCUSSION TITLE
Cover Card: Extra 4th (optional) button

### DISCUSSION THREAD

**Discussion by enazevedo** [piitaya/lovelace-mushroom#1430] [Ideas]
Hi there!

I would like to suggest into the Cover Card, an optional 4th button, triggering the "Favourite" button.

Context:

I have an [Overkiz](https://www.home-assistant.io/integrations/overkiz) integration for my "Somfy Connexoon RTS".
Each blind has 2 entities:
- Cover (with three functions: Open / Close / Stop)
- Button (to move the blind to "My Position", a favourite position I've saved on the original app (not through HA)

![image](https://github.com/piitaya/lovelace-mushroom/assets/53442593/5c6a8a1a-5d58-43e2-b4df-a968da8c7e74)

What I would like to be able to, is to on the "Cover Mushroom card", include a fourth icon, to configure the "Button" one.
I can have them separated (as the gimmick I'm currently using it):
![image](https://github.com/piitaya/lovelace-mushroom/assets/53442593/7e5431cb-f865-40d8-8204-1c783e388b17)
```
square: false
type: grid
cards:
  - type: custom:mushroom-cover-card
    entity: cover.dining_blind
    show_position_control: false
    show_tilt_position_control: false
    show_buttons_control: true
    name: Dining
    secondary_info: none
    primary_info: name
    icon_type: none
  - type: vertical-stack
    cards:
      - type: custom:button-card
        color_type: blank-card
        styles:
          card:
            - height: 40px
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: button.dining_blind_my_position
            content_info: none
            tap_action:
              action: call-service
              service: button.press
              target:
                entity_id: button.dining_blind_my_position
title: Covers
columns: 2
```

But would be great to have it embedded on the Cover-card itself.

I get it that they are two different entities on HA (cover / button), but if thats technically possible to be done, would be a nice touch.

Thanks for your attention reading this, and thank you for the great work on Mushroom cards! Appreciated!
