### DISCUSSION TITLE
Chip Tap Popup

### DISCUSSION THREAD

**Discussion by dankoj** [piitaya/lovelace-mushroom#1509] [Ideas]
Suggestion: Add a Popup option to the Behavior options. When users click on such option, a popup will open with predefined text (typically using templates). I have one possible use in mind zone.home. The home chip shows the number of people home, and when the user taps, a popup should list the names of people at home.

**Comment by BBE-FR** [comment]
For this usage, you can use browser mode to define a pop-up card on tap action:
https://github.com/thomasloven/hass-browser_mod

the code below is for a template card, but the design is working exactly the same on a chip (everything is in the tap-action syntax):

```
type: custom:mushroom-template-card
primary: ""
secondary: ""
icon: mdi:lightbulb
entity: light.0x84ba20fffe4b2581
icon_color: |2-
            {% if is_state(entity, 'on') %} 
             orange
            {% elif is_state(entity, 'off') %} 
             grey
            {% else %}
             grey
            {% endif %}
hold_action:
  action: toggle
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Lumières salon
      content:
        type: vertical-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.0x84ba20fffe4b2581
            name: Petite Lampe
            use_light_color: true
            show_brightness_control: true
            show_color_temp_control: true
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
          - type: custom:mushroom-light-card
            entity: light.prise_lampadaire
            use_light_color: false
            show_brightness_control: false
            show_color_temp_control: false
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
          - type: custom:mushroom-light-card
            entity: light.prise_elephants
            use_light_color: false
            show_brightness_control: false
            show_color_temp_control: false
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
          - type: custom:mushroom-light-card
            entity: light.prise_cerisier
            use_light_color: false
            show_brightness_control: false
            show_color_temp_control: false
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
layout_options:
  grid_columns: 1
  grid_rows: 1

```

the card:
![image](https://github.com/user-attachments/assets/63baa309-e4ff-40d2-b1d7-e2a6ec99c8b9)

when you clic on it, the following pop-up appears:
![image](https://github.com/user-attachments/assets/0b81a4ad-e313-45b8-aebe-1c178b6eab8a)
