### DISCUSSION TITLE
How can I open the more info for a different entity.

### DISCUSSION THREAD

**Discussion by gheydon** [piitaya/lovelace-mushroom#1534] [Q&A] [answered]
Hi,

I have used the template card to create a multiple card which show the light status and the current climate information.
<img width="187" alt="image" src="https://github.com/user-attachments/assets/2219d4f7-5744-47c2-8fd1-94fbaeaa85f2">
Very basic so far. I have configured the single tap action to open the More info for the light, and the hold action to toggle the light on and off. All works great.

However I want to configure the double tap action to open the More info for the air conditioner. I am not sure if this is possible, I found that I could do this from a service but there is no way to call a service. 

Any help or ideas will be great.
Thanks.

**Comment by BBE-FR** [comment]
For this usage, you can use browser mode to define a pop-up card on tap action:
https://github.com/thomasloven/hass-browser_mod

the code below is for a template card, but the design is working exactly the same on a chip (everything is in the tap-action syntax):

```
type: custom:mushroom-template-card
primary: ""
secondary: ""
icon: mdi:lightbulb
entity: light.0x84ba20fffe4b2581
icon_color: |2-
            {% if is_state(entity, 'on') %} 
             orange
            {% elif is_state(entity, 'off') %} 
             grey
            {% else %}
             grey
            {% endif %}
hold_action:
  action: toggle
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Lumières salon
      content:
        type: vertical-stack
        cards:
          - type: custom:mushroom-light-card
            entity: light.0x84ba20fffe4b2581
            name: Petite Lampe
            use_light_color: true
            show_brightness_control: true
            show_color_temp_control: true
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
          - type: custom:mushroom-light-card
            entity: light.prise_lampadaire
            use_light_color: false
            show_brightness_control: false
            show_color_temp_control: false
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
          - type: custom:mushroom-light-card
            entity: light.prise_elephants
            use_light_color: false
            show_brightness_control: false
            show_color_temp_control: false
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
          - type: custom:mushroom-light-card
            entity: light.prise_cerisier
            use_light_color: false
            show_brightness_control: false
            show_color_temp_control: false
            show_color_control: false
            collapsible_controls: true
            tap_action:
              action: toggle
layout_options:
  grid_columns: 1
  grid_rows: 1

```

the card:
![image](https://github.com/user-attachments/assets/63baa309-e4ff-40d2-b1d7-e2a6ec99c8b9)

when you clic on it, the following pop-up appears:
![image](https://github.com/user-attachments/assets/0b81a4ad-e313-45b8-aebe-1c178b6eab8a)

You just have to change the pop up content to use this card:
https://github.com/thomasloven/lovelace-more-info-card
