### DISCUSSION TITLE
Tempalting navigation path in tap action of template card

### DISCUSSION THREAD

**Discussion by genebean** [piitaya/lovelace-mushroom#1631] [Q&A]
Given the code below:

```yaml
icon: "{{ state_attr(entity,'icon') }}"
tap_action:
  action: navigate
  navigation_path: /this-dashboard/some-subview
```

Is there any way to use templating in the `navigation_path` value? I tried but it rendered literally. I am using a template card as the card inside the grid of auto-entities and want to put something like `/this-dashboard/"{{ state_attr(entity,'area_id') }}"` as the value there so that each card in the grid goes to `/this-dashboard/subview-named-for-area`.
