### DISCUSSION TITLE
Room card

### DISCUSSION THREAD

**Discussion by tivoo** [piitaya/lovelace-mushroom#302] [Ideas]
Feature request: Room Card from Minimalist UI:
https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_room/

**Comment by piitaya** [comment]
There already is an issue about that #55. Mushroom is inspired from Minimalist but the goal is not to provide all the Minimalist features in Mushroom.

**Comment by tivoo** [comment]
You're right, missed that. Thanks!

**Comment by Gnol86** [comment]
I make this with [Stack In Card](https://github.com/custom-cards/stack-in-card) and [Lovelace Mini Graph Card](https://github.com/kalkih/mini-graph-card) 
<img width="346" alt="image" src="https://user-images.githubusercontent.com/24519929/173931111-6a6e0862-5efb-4214-8a0e-44ff192328f9.png">
```
type: custom:stack-in-card
mode: vertical
cards:
  - type: custom:mushroom-template-card
    primary: Salon
    secondary: '{{ states.sensor.capteur_temperature_salon_temperature.state }}°C'
    icon: mdi:sofa
    icon_color: "{%\_if states.input_boolean.salon_presence.state == 'on' %}amber{% endif %}"
  - type: custom:mushroom-chips-card
    card_mod:
      style: |
        ha-card {
          --chip-box-shadow: none;
          --chip-background: none;
        }
    alignment: end
    chips:
      - type: conditional
        conditions:
          - entity: media_player.salon
            state: playing
        chip:
          type: entity
          entity: media_player.salon
          use_entity_picture: true
          content_info: none
      - type: conditional
        conditions:
          - entity: media_player.android_tv
            state: 'on'
        chip:
          type: entity
          entity: media_player.android_tv
          use_entity_picture: true
          content_info: none
      - type: conditional
        conditions:
          - entity: cover.salon
            state: close
        chip:
          type: entity
          entity: cover.salon
          content_info: none
      - type: conditional
        conditions:
          - entity: binary_sensor.porte_salon_contact
            state: 'on'
        chip:
          type: entity
          entity: binary_sensor.porte_salon_contact
          content_info: none
      - type: conditional
        conditions:
          - entity: binary_sensor.fenetre_salon_4_contact
            state: 'on'
        chip:
          type: entity
          entity: binary_sensor.fenetre_salon_4_contact
          content_info: none
      - type: conditional
        conditions:
          - entity: binary_sensor.sensor_salon_motion
            state: 'on'
        chip:
          type: entity
          entity: binary_sensor.sensor_salon_motion
          content_info: none
      - type: light
        entity: light.salon
        content_info: none
        use_light_color: true
        tap_action:
          action: more-info
        hold_action:
          action: more-info
        double_tap_action:
          action: more-info
  - type: custom:mini-graph-card
    hours_to_show: 12
    points_per_hour: 6
    height: 70
    line_width: 0
    show:
      name: false
      icon: false
      state: false
      points: false
      labels: false
      fill: fade
    entities:
      - sensor.capteur_temperature_salon_temperature
```
