### DISCUSSION TITLE
Custom font-size setting across all cards

### DISCUSSION THREAD

**Discussion by wizake** [piitaya/lovelace-mushroom#438] [Ideas]
Hi

Would it be possible to have a global setting to increase a bit the font size used by the cards and chips? 
Not necessarily accept any value, but maybe a couple of 'steps' like 'medium', 'large',  and so on.
On my phone the text is kinda small, and sometimes I struggle to read it (I know I need better glasses)

Thanks

**Comment by piitaya** [comment]
Hi 🙂

You can customize the size on chips using theme.

Example :
```yaml
# Chips
mush-chip-spacing: 8px
mush-chip-padding: 0 12px
mush-chip-height: 36px
mush-chip-border-radius: 18px
mush-chip-font-size: 1em # relative to chip height
mush-chip-font-weight: bold
mush-chip-icon-size: 1.5em # relative to chip height
```

All themes variables are available on https://github.com/piitaya/lovelace-mushroom-themes. I planned to add more variables soon to customize card icon size for example.

**Comment by wizake** [comment]
that's awesome! thanks a lot!

**Comment by T1ppes** [comment]
Sorry to ask a dumb question, but where exactly do I need to put these variables? Could I ask you to add a example on the Mushroom Theme GitHub Readme please?

**Reply by redphx** [reply]
Edit your theme at `/config/themes/mushroom/mushroom.yaml`

**Reply by T1ppes** [reply]
Ah thank you. Will these settings stick, even when updating the theme via HACS or will it get overwritten?

**Reply by redphx** [reply]
Oh I think you'll need to do these steps:  

1. Add these lines to `/config/configuration.yaml`:
```
frontend:
    themes: !include themes.yaml
```
2. Create `/config/themes.yaml` with this content for example:
```
Mushroom:
    mush-chip-height: 42px
    
    modes:
        light: {}
        dark: {}
```
3. Go to your profile's page, and change Theme to "Mushroom" (you might need to restart HA first).
