### DISCUSSION TITLE
Date / Time Card

### DISCUSSION THREAD

**Discussion by herrzettpunkt** [piitaya/lovelace-mushroom#655] [Q&A]
Hello,

I'd like to have a simple entity card with time as primary and date as secondary information. Is it possible to archive this with the template card by editing the primary and secondary information fields? I don't know how I can put an entity in these fields (if it's even possible) like in the screenshot.

Thank you!

<img width="235" alt="Bildschirmfoto 2022-07-23 um 22 51 06" src="https://user-images.githubusercontent.com/89742641/180622554-6d8353b6-6c5c-4b41-ad12-d46f8f338f81.png">

**Comment by SendNukez** [comment]
Yes, it is possible.
If you want to use different time formats, have a look at [this](https://docs.python.org/3.8/library/datetime.html#strftime-and-strptime-format-codes).

```yaml
type: custom:mushroom-template-card
primary: '{{ as_timestamp(now()) | timestamp_custom("%H:%M") }}'
secondary: '{{ as_timestamp(now()) | timestamp_custom("%d. %b %Y") }}'
icon: mdi:calendar
```
