### DISCUSSION TITLE
Default entity icon color for template card

### DISCUSSION THREAD

**Discussion by metbril** [piitaya/lovelace-mushroom#727] [Q&A]
I'm trying to set the icon color for a template card to the default entity card color. I've tried `icon_color: default`, `icon_color: enabled`, `icon_color: standard` and `icon_color: ''` but all of those do not work.

- Empty color shows as 'disabled'
- `''` (single quotes) shows as black
- `default` and `standard` also show as black
- `red`, `green` or `blue` show as expected.

```
type: vertical-stack
cards:
  - type: custom:mushroom-entity-card
    entity: sun.sun
  - type: custom:mushroom-template-card
    entity: sun.sun
    primary: Sun Elevation
    secondary: '{{ state_attr(''sun.sun'',''elevation'') }} degrees'
    icon: mdi:sun-angle
    badge_icon: ''
    icon_color: ''
```

![image](https://user-images.githubusercontent.com/559346/190088207-6ff083aa-5111-4470-b446-afa112f171ce.png)

What is the template syntax for the current default (theme) entity color?
