### DISCUSSION TITLE
Slider on Climate card

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [piitaya/lovelace-mushroom#761] [Ideas]
Please forgive me if this is possible. I am new to the Mushroom world, and believed the generic design the light card uses would be available to the other cards, like, in my case, the climate card. 
More specifically the slider. Currently I tried the default settings:
```
  - type: custom:mushroom-climate-card
    entity: climate.heater_office
    fill_container: true
    show_temperature_control: true
    collapsible_controls: true
    hvac_modes:
      - heat
```
to get:

<img width="545" alt="Schermafbeelding 2022-10-05 om 11 27 44" src="https://user-images.githubusercontent.com/33354141/194028133-0c48851e-d1f3-421d-9527-c6fdcca89675.png">

and could not find a setting in the documentation to add a slider. A slider would be of great help on a mobile device particularly.

please let me know if this would be possible, or, maybe open for a FR if not yet possible .

Thanks!
