### DISCUSSION TITLE
Small light button with a slider for dimming popping up on long-press?

### DISCUSSION THREAD

**Discussion by magune** [piitaya/lovelace-mushroom#774] [Ideas]
I am building a dashboard with mushroom cards, and have loads of light buttons that I want to use for on/off or dimming (slider).

The problem is that since I want to be able to control dimming with a slider, all light cards take up a huge amount of space on the dashboard, making it very cluttered as well. I'd like to be able to have a small light button with only bulb-icon & name in it, and then a long-press on the button should popup a slider for dimming. 

Similar to Apple's Home app, more or less.

Currently, the mushroom light card do popup the standard HA "advanced" dialog with loads of advanced stuff on a long-press; but it is way too complicated to look nice and be family friendly -  I just want the dimming slider and nothing else, in the same "theme" look & field as the mushroom card itself.

Any chance to get this into mushroom light card, or does anyone know about a different light card that does this?

**Comment by piitaya** [comment]
Hello, more info dialog will be improved in a next Home Assistant updates (that's in the road map 😛) to provide directly user friendly controls (like in Apple Home app)

**Comment by antonio1475** [comment]
@magune  I'm doing this already with browser_mod:
```
type: custom:mushroom-light-card
entity: light.despacho
name: Office
hold_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content:
        type: custom:mushroom-light-card
        entity: light.despacho
        show_brightness_control: true
        show_color_temp_control: true
```
You can remove everything except the slider in the popup card. Just prepare it first to your liking in the mushroom editor (space in name, secondary info none, icon type none, etc).

https://user-images.githubusercontent.com/63130724/196925689-cd41f8e4-3ee2-491c-b012-62e4754e4fe4.mp4

The difficult option is another dashboard like [Minimalist UI](https://ui-lovelace-minimalist.github.io/UI/), with its [Light Card](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_light/) and [Light Popup](https://ui-lovelace-minimalist.github.io/UI/usage/popups/popup_light/)
