### DISCUSSION TITLE
Adding climate/temperature controls into right of template card

### DISCUSSION THREAD

**Discussion by cadwizzard** [piitaya/lovelace-mushroom#808] [General]
Is it possible to call in the temperature controls like in the climate card into the template card? 

The reason for asking is I need to control the icons/badges better than I think its possible with the climate card with something like (badge not yet set up for change in this example):
![template](https://user-images.githubusercontent.com/7688705/199056808-85eb7042-b905-4eff-bc24-c6229d495c5d.jpg)

But I also need the temperature controls, and i've tried using horizontal stack, but end up with something like this
![stack](https://user-images.githubusercontent.com/7688705/199057222-78869f6e-df0b-48e4-befe-e9b7e7875399.jpg)

I have to keep the card compact like the original mushroom climate card, as there are over 20 radiators I need on one dashboard, but I need to see if they are on and/or calling for heat. My TRV's don't have a 'heating' state, so the badge doesn't work on the climate control, leaving me to have to build a special card and add some logic to determine the heating (will be something simple like setpoint>temperature once I figure out how to add that).

Any solution via template card or the ability to customise icons more in the climate card would be perfect. I've spent 'a while'/hours trying to figure this out, so any suggestions appreciated :)

**Comment by antonio1475** [comment]
Yes. I've done this with a combination of mushroom template & climate cards within a [vertical-stack-in-card](https://github.com/ofekashery/vertical-stack-in-card) (which removes the borders of the inside cards).

1. Top-left: Template to show all the info that I want
2. Top-right: temperature
3. Bottom: Modes

![Screenshot from 2022-11-19 23-13-37](https://user-images.githubusercontent.com/63130724/202873430-9c563981-ff5a-4d52-8c06-a61f1a3db599.png)


```
type: custom:vertical-stack-in-card
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-template-card
        icon: >-
          {% if is_state("climate.home", "auto")%}mdi:thermostat-box-auto{% elif
          is_state("climate.home", "heat")%}mdi:radiator{% elif
          is_state("climate.home", "off")%}mdi:radiator-off{% else
          %}mdi:thermostat-box{% endif%}
        icon_color: >-
          {% if is_state("climate.home", "auto")%}green{% elif
          is_state("climate.home", "heat")%}deep-orange{% elif
          is_state("climate.home", "off")%}grey{% else %}grey{% endif%}
        primary: Calefacción
        secondary: >
          {{ states('climate.home') | title }}{% if
          states('sensor.home_heating')|float > 0 %} |
          {{states('sensor.home_heating')|round(0) }}%{% else %}{% endif %}
        entity: climate.home
        tap_action:
          action: more-info
        double_tap_action:
          action: none
        hold_action:
          action: none
        badge_color: >-
          {% set caldera = states('sensor.home_heating')|float %}
          {% if is_state_attr("climate.home", "hvac_action","idle")%}disabled
          {% elif 0 < caldera < 10 %}amber
          {% elif 10 < caldera < 40 %}orange
          {% elif 40 < caldera < 80 %}deep-orange
          {% elif 80 < caldera < 101 %}red
          {% else %}yellow{% endif %}
        badge_icon: >-
          {% if is_state_attr("climate.home","hvac_action","idle")%}mdi:clock-outline{% elif
          is_state_attr("climate.home", "hvac_action","heating")%}mdi:fire{% elif
          is_state_attr("climate.home", "hvac_action","off")%}{% else
          %}mdi:help{% endif%}
      - type: custom:mushroom-climate-card
        entity: climate.home
        show_temperature_control: true
        collapsible_controls: false
        hvac_modes: []
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
        primary_info: none
        secondary_info: none
        icon_type: none
  - type: custom:mushroom-climate-card
    entity: climate.home
    show_temperature_control: false
    collapsible_controls: false
    hvac_modes:
      - heat
      - auto
      - 'off'
    tap_action:
      action: none
    primary_info: none
    secondary_info: none
    icon_type: none
    hold_action:
      action: none
    double_tap_action:
      action: none
    fill_container: false
```
