### DISCUSSION TITLE
add to fan card preset_modes

### DISCUSSION THREAD

**Discussion by andrey170183** [piitaya/lovelace-mushroom#893] [Ideas]
It would be great to switch modes by buttons from the card

**Comment by RickeyWard** [comment]
See: https://github.com/piitaya/lovelace-mushroom/issues/1032

![image](https://user-images.githubusercontent.com/342468/229974164-7f0adc47-1f36-47e0-adea-264222d1870a.png)
![image](https://user-images.githubusercontent.com/342468/229974967-16c6b420-1ae5-4cf0-8694-afa613a98c50.png)

Not clear if you meant speeds by 'modes' but its a start.

**Comment by andrey170183** [comment]
Cool 👏🏻👍🏻 Thanks!

ср, 5 апр. 2023 г. в 12:41, DiamondDrake ***@***.***>:

**Comment by andrey170183** [comment]
```
type: custom:mushroom-fan-card
entity: fan.airdog_purifier
name: Очиститель воздуха
presets:
  - value: 25
    icon: mdi:fan-speed-1
  - value: 50
    icon: mdi:fan-speed-2
```

it does not work for me, presets buttons does not showing

![1](https://github.com/piitaya/lovelace-mushroom/assets/42129962/8bca00fa-e471-43f0-9b8a-a2de925c6a0a)
