### DISCUSSION TITLE
Show person image in template chip card

### DISCUSSION THREAD

**Discussion by MarcelBochtler** [piitaya/lovelace-mushroom#901] [Q&A] [answered]
Hi,
I'm trying to create an enhanced version of a chip using a template.
I want to display a person's profile picture, the person's state and the battery state of a device.
I've already succeeded with the state and the battery level, but I can't figure out how to display the profile picture.

This is what I'm getting when setting the path of the profile picture as `Picture (will replace the icon)`:
![image](https://user-images.githubusercontent.com/4022103/208269469-94f486bd-bc36-4887-9612-ce9a6a3a2f7d.png)

This is my current config:
```yml
type: template
icon: ''
content: >-
  {{states('device_tracker.marcel_pixel5').capitalize()}} | {{
  states('sensor.pixel_5_battery_level') }}%
entity: person.marcel
picture: /config/image/28e5188bfa6c046d9b9dd692e4a5670f/512x512
```

**Comment by MarcelBochtler** [comment, marked as answer]
Figured it out:
I can use the person attribute `entity_picture` as `Picture`. The whole config looks like this:
```yml
type: template
content: >-
  {{states('device_tracker.marcel_pixel5').capitalize()}} | {{
  states('sensor.pixel_5_battery_level') }}%
entity: person.marcel
picture: '{{ state_attr(''person.marcel'', ''entity_picture'') }}'
```
