### ISSUE TITLE
[Bug]: Boarders with Vertical stacks 

### ISSUE THREAD

**Issue by tofrie** [piitaya/lovelace-mushroom#1008]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I used vertical stacks and got a boarder in it.

### Expected Behavior

There should be no boarder.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Safari 
- HA Version: latest
- Mushroom:
```

**Comment by tofrie** [comment]
![9E025F70-7C67-4141-AC14-24BC227365F5](https://user-images.githubusercontent.com/60553702/216790835-61760dca-7442-4186-a5d0-0734af78271c.png)

**Comment by tofrie** [comment]
````
type: custom:vertical-stack-in-card
title: Kamin
cards:
  - type: custom:mushroom-fan-card
    entity: fan.burn_level_living_room
    icon_animation: false
    collapsible_controls: true
    show_percentage_control: true
    show_oscillate_control: false
    name: Level
    primary_info: state
    secondary_info: name
  - type: custom:mushroom-entity-card
    entity: sensor.phase_living_room
    name: Phase
    icon: mdi:fire
    primary_info: state
    secondary_info: name
  - type: conditional
    conditions:
      - entity: sensor.time_to_new_fire_wood_living_room
        state_not: '0:00:00'
    card:
      type: custom:mushroom-entity-card
      entity: sensor.time_to_new_fire_wood_living_room
      name: Zeit zum Nachlegen
      icon: mdi:clock-outline
      primary_info: state
      secondary_info: name
  - type: conditional
    conditions:
      - entity: sensor.time_to_new_fire_wood_living_room
        state: '0:00:00'
    card:
      type: custom:mushroom-template-card
      primary: Jetzt!
      secondary: Zeit zum Nachlegen
      icon: mdi:bell-ring-outline
      tap_action:
        action: none
      hold_action:
        action: none
      double_tap_action:
        action: none
      icon_color: yellow
````
