### ISSUE TITLE
[Bug]: Select Card does not auto-update its state

### ISSUE THREAD

**Issue by pedolsky** [piitaya/lovelace-mushroom#1017]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

First: Many thanks for providing a select card!

The problem: If the state is set by a `select`'s configuration or via automation, the card only updates after refreshing the dashboard. 
In contrast, when using a default `entities` card, the card updates immediately. 

### Expected Behavior

No need for refreshing the page to see the new state on the card

### Context

YAML state
```

template:

- select:

  - name: Szenen Lounge
    unique_id: '202302071601'
    state: "{{ states('input_text.szenen_lounge') }}"
    options: |-
      {% set phrase =  ['…', 'Aus'] %}
      {% set x = state_attr('light.lounge', 'hue_scenes') %}
      {{ phrase + (x if x is not none else ['N/A']) |list |sort }}
    select_option:
    - variables:
        x: lounge
        light: light.{{ x }}
        input: "{{ 'input_text.szenen_' ~ x }}"

    - service: input_text.set_value
      data:
        value: "{{ option }}"
      target:
        entity_id: "{{ input }}"

    - if:
      - "{{ option not in ['…', 'Aus'] }}"
      then:
      - service: scene.turn_on
        data:
          transition: 5
        target:
          entity_id: scene.{{ x }}_{{ option |slugify }}
      else:
      - stop: 'Option …/Aus gewählt'

```

Automation:

```

automation:

  variables:
    t: '{{ trigger.entity_id }}'
    select: |-
      {% set select = 'select.szenen_' ~ t.split('.')[1] %}
      {{ select }}
    optionen: |-
      {% set opt = state_attr(t, 'hue_scenes') %}
      {{ opt }}

  trigger:
  - platform: state
    entity_id:
    - light.lounge
    - light.anrichte
    - light.wohnen
    from:
    - 'on'
    - 'off'
    to:
    - 'on'
    - 'off'

  action:
  - service: select.select_option
    data:
      option: |-
        {{ '…' if trigger.to_state.state == 'on' and states(select) not in optionen else 'Aus' }}
    target:
      entity_id: "{{ select }}"

```

### Environment

```markdown
- Browser: Chrome 109.0.5414.112, Safari 16.3
- HA Version: core-2023.2.2
- Mushroom: 2.5.3
```

**Comment by piitaya** [comment]
Do you have the error on every device (phone, computer, etc...) ?
I'm unable to reproduce the issue with the latest Mushroom version so I can not help.

**Comment by pedolsky** [comment]
It's the combination of Mush Light Card and Mush Select Card (and ev. Tile Card), that causes the problem:

```

type: grid
title: ' '
square: false
columns: 1
cards:
  - type: grid
    title: ' '
    square: false
    columns: 2
    cards:
      - type: tile
        entity: light.anrichte
      - type: custom:mushroom-select-card
        entity: select.szenen_anrichte
        secondary_info: none
        icon_type: none
        primary_info: none
  - type: custom:mushroom-light-card
    entity: light.anrichte
    icon_type: none
    primary_info: none
    show_brightness_control: true
    collapsible_controls: true
    use_light_color: true
    show_color_control: true
    show_color_temp_control: true
    secondary_info: none

```

But I have to do further investigation.
