### ISSUE TITLE
[Bug]: Buttons scaling on vacuum card

### ISSUE THREAD

**Issue by maxyvon** [piitaya/lovelace-mushroom#1034]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The buttons of the vacuum card do not scale/resize properly when the layout is set to horizontal. (Second card on the screenshot) Other layouts work fine.

### Expected Behavior

The vacuum card command buttons should be scaled/resized like the climate card button. (See screenshot)

### Steps To Reproduce

1. Add the vacuum card
2. Select command buttons
3. Set layout to horizontal
4. Scale your browser screen to resize the cards or use your phone
5. The button won’t scale 

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: 
  • iOS: Safari, Homeassistant app
  • Windows: Chrome
- HA Version: 2023.2.5
- Mushroom: 2.5.3
```

### Anything else?

![080508AB-33EC-4360-871D-B27CB4BCC579](https://user-images.githubusercontent.com/44422604/220731088-d33374eb-2f6d-479e-a3f5-cdca3108f018.jpeg)

**Comment by piitaya** [comment]
I tried to fix the issue for all cards so it should work for the vacuum. 
If you look in your browser console, what Mushroom version do you hav? Also, what browser do you use?

I look at the screenshot below, it works for me.
![CleanShot 2023-03-07 at 22 12 51@2x](https://user-images.githubusercontent.com/5878303/223554059-bbbcf9b7-dbe2-4228-8f4b-c0a9473041d7.png)

```yaml
type: custom:mushroom-vacuum-card
entity: vacuum.ground_floor_vacuum
layout: horizontal
commands:
  - on_off
  - start_pause
  - stop
  - locate
  - clean_spot
  - return_home
primary_info: none
secondary_info: none
```
