### ISSUE TITLE
[Bug]: Mushroom cards are incompatible with sensor display precision setting in 2023.3 beta

### ISSUE THREAD

**Issue by krazos** [piitaya/lovelace-mushroom#1035]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

HA 2023.3 is introducing a new display precision setting for sensors:

https://rc.home-assistant.io/blog/2023/02/22/release-20233/#sensor-precision

In beta testing 2023.3.0b0 and 2023.3.0b1, a number of my mushroom entity and entity chip cards for temperature sensors -- particularly my average temperature sensors created with the new sensor group that was introduced in 2023.2 -- are showing as many as 13 decimal places instead of the 1 decimal place that I have set using the new display precision setting for the sensors.

### Expected Behavior

The mushroom entity and entity chip cards (and possibly) others should be updated to respect the sensor display precision setting to ensure compatibility with 2023.3+.

#### State and Attribute Data for Sample Sensor
**Entity**:
```yaml
sensor.great_room_average_temperature
Great Room Average Temperature
```
**State**:
```yaml
69.0033333333333
```

**Attributes**:
```yaml
state_class: measurement
entity_id: sensor.great_room_ecobee_thermostat_temperature, sensor.main_floor_ecobee_sensor_temperature, sensor.espresense_great_room_sht30_temperature
unit_of_measurement: °F
device_class: temperature
icon: mdi:thermometer
friendly_name: Great Room Average Temperature
```

### Environment

```markdown
- Browser: Chrome and iOS App
- HA Version: 2023.3.0b1
- Mushroom: 2.5.3
```
