### ISSUE TITLE
[Feature]: Scene selector 

### ISSUE THREAD

**Issue by HyperCriSiS** [piitaya/lovelace-mushroom#1048]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

It is not possible to select scenes 

### Describe the solution you'd like

It would be nice to have a button which opens a scene selector :)

**Comment by Majumafoo** [comment]
I've been using chips as a solution to this problem
Most of the complexity comes from the chips lighting up depending on which scene is active, which is done by referencing a text_input.
You could easily avoid that and just have a chip activate a scene.
![image](https://user-images.githubusercontent.com/45857221/231243463-508b35eb-c5ee-4498-b59b-c410b7c1bae1.png)

YAML:
```
type: custom:mushroom-chips-card
chips:
  - type: template
    icon: mdi:lightbulb-off-outline
    content: 'Off'
    icon_color: |-
      {% if states('input_text.active_scene_office') == 'off' %}
        white
      {% else %}
        disabled
      {% endif %}
    tap_action:
      action: call-service
      service: input_text.set_value
      target:
        entity_id: input_text.active_scene_office
      data:
        value: 'off'
    entity: office Off
  - type: template
    entity: scene.office_low
    icon: mdi:brightness-4
    icon_color: |-
      {% if states('input_text.active_scene_office') == 'low' %}
        #FFC896
      {% else %}
        disabled
      {% endif %}
    content: Low
    tap_action:
      action: call-service
      service: input_text.set_value
      target:
        entity_id: input_text.active_scene_office
      data:
        value: low
  - type: template
    entity: office Max
    icon: mdi:brightness-7
    icon_color: |-
      {% if states('input_text.active_scene_office') == 'max' %}
        #FFC896
      {% else %}
        disabled
      {% endif %}
    content: Max
    tap_action:
      action: call-service
      service: input_text.set_value
      target:
        entity_id: input_text.active_scene_office
      data:
        value: max
```
