### ISSUE TITLE
Select 'Attribute' as information source for entity card

### ISSUE THREAD

**Issue by Gurutasker** [piitaya/lovelace-mushroom#109]
Many sensors and entities store information as attributes. 
Often this is desired to be displayed on an entity card, or in some cases other cards instead of the 'state' of the entity.

For example, a sensor from a router integration may show a port status as 'up' and the attributes information such as IP Address, RX/TX information.

If attributes could be selected as an information source in the entity card this would allow for significantly more flexibility in the information shown. 

As an added feature and in keeping with the intent of the project, the attributes could be enumerated from the entity to be selectable in a drop-down list.

Entity Card

Primary information source 
  -> Attributes
     -> _Available attributes listed here_

**Comment by cyrilphoenix71** [comment]
+100000

**Comment by piitaya** [comment]
We already discussed about that https://github.com/piitaya/lovelace-mushroom/issues/45. We do not plan to add attribute  on entity card for now because this can be solve with template-card because it's an advanced usage.
Unlike the state, attributes can't be formatted and translated. If we add attribute, we will have a lot of issues : "add unit to attribute", "allow to select 2 attributes", etc... So we prefer for now to use template for that to add maximum flexibility.

Note : we will add `more-info` tap action to template card soon 🙂

```
type: custom:mushroom-entity-card
primary: My router
secondary: {{ state_attr('sensor.my_router', 'ip_address') }} 
icon: mdi:router
color: blue
```

**Comment by luixal** [comment]
I was going to ask for something similar, instead of attributes, values from another entity. In my case, almost all of my switches have a power meter inside, which is configured in HA as **three** different entities:
 
![image](https://user-images.githubusercontent.com/615268/153905848-24394c45-4c07-4a53-933a-53f843ce1849.png)

It would be nice to be able to select the value of one of those entities here:

![image](https://user-images.githubusercontent.com/615268/153905792-d37063db-5e41-48fd-9141-918ca8a72e8e.png)

so I can show consumption value while turned on. I've managed to do it with an entity card. If someone else gets here looking for something like this, this is how I did it:

```yaml
- type: custom:mushroom-template-card
  entity: switch.lamapara_salon_mss310_main_channel
  icon: mdi:floor-lamp-outline
  icon_color: "{% if is_state('switch.lamapara_salon_mss310_main_channel', 'on') %} orange {% endif %}"
  primary: Lámpara
  secondary: >
    {% if (float(states('sensor.lamapara_salon_mss310_power_w_main_channel')) > 0) and is_state('switch.lamapara_salon_mss310_main_channel', 'on') %}
      {{ states('sensor.lamapara_salon_mss310_power_w_main_channel') }} W
    {% endif %}
  vertical: false
```

and this is how it looks:

![image](https://user-images.githubusercontent.com/615268/153906261-a75b198e-4f7d-47bf-81a9-01c9a986bc70.png)
