### ISSUE TITLE
[mushroom-lock-card]: Confirmation on unleash button

### ISSUE THREAD

**Issue by lpercetti** [piitaya/lovelace-mushroom#1097]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

When clicking on the unleash icon, the door is triggered for opening without any confirmation. If you're connected remotely, then you're not able to do anything, and the door stays open. It would be great to have to ability to enable a confirmation for such button, so it avoid opening remotely by mistake while scrolling in the interface.

### Describe alternatives you've considered

I tried to see if I could do it myself in the code, but I didn't manage. An alternative is to totally remove the button.

**Comment by SpaceFahad** [comment]
Same request here,

I hope they support adding a confirmation just like how you would be able to add it to a button in HA

confirmation:
    text:

**Comment by SpaceFahad** [comment]
I encountered the same problem when I once unlocked my external gate which can only be locked again manually/physically.

You can add a confirmation text requiring you to press another button again to confirm the action. 

Here is how I did it with a mushroom entity card:


`
type: custom:mushroom-entity-card
tap_action:
  action: call-service
  **confirmation:
    text: Are you sure?**
  service: automation.trigger
  target:
    entity_id: automation.A.unlocked_external_door
  data:
`

Hope that helps!

**Comment by chatziko** [comment]
+1. `tap_action` is  very limited workaround for the lock card, it's much easier to use the icons.

**Comment by jasii** [comment]
Even just adding a vibration on press would help with this.

**Comment by antgustech** [comment]
I used this at first:
```

type: custom:mushroom-lock-card
entity: lock.door
name: "xxx"
fill_container: false
tap_action:
  action: toggle
  confirmation:
    text: Är du säker på att du vill låsa/låsa upp?
```
But that only added a confirmation prompt on the card and not the button in the card.

I simply ended up ditching the mushroom lock card and use the regular custom button card instead. I really must have a confirmation on this lock:

```
type: custom:button-card
tap_action:
  action: call-service
  service: lock.lock
  service_data:
    entity_id: lock.door
  confirmation:
    text: Är du säker på att du vill låsa/låsa upp?
entity: lock.door
name: xxx
show_state: true
show_icon: false

```
