### ISSUE TITLE
[Bug]: <title>

### ISSUE THREAD

**Issue by thomaszlow** [piitaya/lovelace-mushroom#1114]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The states like `on`, `off`, `open`, `closing`, `closed` in cards likes "Light", "Cover Card" are not translated in the local language which is selected in the Home Assistant profile. Instead they are displayed in English.
However, `last-changed` and `last-updated` are translated correctly.
States of non-mushroom cards are translated correctly.

In the screenshot `secondary_info` type of item **Esstisch** was changed to `last-updated` to demonstrate that this is translated correctly into German. All other `secondary_info` fields show English.

![Bildschirmfoto 2023-04-17 um 19 26 28](https://user-images.githubusercontent.com/79666256/232563376-d87e2b3b-c8d5-44d8-b73c-d1c6841554d1.png)

### Expected Behavior

When "German" is selected as language in the user profile, the states should be displayed like below:

- `on` -> `An` 
- `off` -> `Aus`
- `open` -> `Offen`
- `closing` -> `Schließt`
- `closed` -> `Geschlossen`

### Steps To Reproduce

1. Select a language which is not **English** in the user profile, e.g. **German** or **Spanish**
2. Create a mushroom card like `Light` or `Cover`
3. Leave the `secondary_info` as default or change it to `state`
4. Create a default (non-mushroom) card for the light or cover to compare

### Context

YAML state
```
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Lampen
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:mushroom-light-card
        icon: hue:ensis-up
        fill_container: false
        name: Esstisch
        secondary_info: last-updated
        use_light_color: false
        show_brightness_control: true
        show_color_temp_control: false
        show_color_control: false
        collapsible_controls: true
        entity: light.wohnzimmer_essen
      - type: custom:mushroom-light-card
        icon: mdi:ceiling-light
        name: Couch
        entity: light.wohnzimmer_couch
        show_brightness_control: true
        collapsible_controls: true
      - type: custom:mushroom-light-card
        entity: light.wohnzimmer_sessel
        name: Sessel
        show_brightness_control: true
        collapsible_controls: true
      - type: custom:mushroom-light-card
        name: Durchgang
        entity: light.wohnzimmer_durchgang
  - type: custom:mushroom-light-card
    entity: light.stehlampe_zuiver
    show_color_control: true
    show_color_temp_control: true
    use_light_color: true
    show_brightness_control: true
    collapsible_controls: true
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:mushroom-light-card
        entity: light.bucherregal
        name: Bücherregal
        show_brightness_control: true
        collapsible_controls: true

```

### Environment

```markdown
- Browser: Chrome 112.0.5615.49 
- HA Version: 2023.4.4
- Mushroom: 2.7.0
```
