### ISSUE TITLE
fill_container is not working in decluttering_templates

### ISSUE THREAD

**Issue by yohaybn** [piitaya/lovelace-mushroom#1133]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

when I use fill_container in decluttering_templates. the card is not fill the container.

this is my template:
```
  template_ac_climate:
    card:
      type: custom:mushroom-climate-card
      entity: '[[entity_id]]'
      name: '[[name]]'
      show_temperature_control: true
     fill_container: true
      collapsible_controls: true
      hvac_modes:
        - cool
        - heat
        - 'off'
      tap_action:
        action: toggle
```
and the results:
![image](https://user-images.githubusercontent.com/7513920/235339764-b08a9070-5236-4862-bfb0-f4ac6e1232ea.png)

### Expected Behavior

card will fill the container.

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.4.6
- Mushroom: 2.7.1
```
