### ISSUE TITLE
[Bug]: Chips values is not right

### ISSUE THREAD

**Issue by ggagnidze** [piitaya/lovelace-mushroom#1137]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Text in chip cards shows localisation names

### Expected Behavior

Test in chip cards shows raw data

### Steps To Reproduce

: custom:mushroom-chips-card
chips:
  - type: alarm-control-panel
    entity: alarm_control_panel.home_alarm
  - type: weather
    entity: weather.forecast_ghome
    show_conditions: true
    show_temperature: true
  - type: entity
    entity: sensor.airpurifierpurifier_temperature
    icon_color: deep-purple
    icon: mdi:sofa-outline
  - type: entity
    entity: sensor.bedroom_sensor_th_temperature
    icon: mdi:bed-queen-outline
    use_entity_picture: false
    icon_color: orange
    name: Температура
  - type: entity
    entity: sensor.mh_z19_co2_value
    icon_color: light-blue
alignment: center
view_layout:
  position: main

### Context

YAML state
```yaml

temperature: 0.5temperature_unit: %C2%B0Chumidity: 75pressure: 1021.3pressure_unit: hPawind_bearing: 279.1wind_speed: 16.9wind_speed_unit: km/hvisibility_unit: kmprecipitation_unit: mmforecast:  - condition: partlycloudy    datetime: '2023-05-09T07:00:00+00:00'    wind_bearing: 270.4    temperature: 12    templow: 0.4    wind_speed: 13.7    precipitation: 0  - condition: sunny    datetime: '2023-05-10T07:00:00+00:00'    wind_bearing: 262.5    temperature: 14.5    templow: 0.6    wind_speed: 12.2    precipitation: 0  - condition: cloudy    datetime: '2023-05-11T07:00:00+00:00'    wind_bearing: 31    temperature: 12.2    templow: 4.5    wind_speed: 13    precipitation: 0.1  - condition: sunny    datetime: '2023-05-12T07:00:00+00:00'    wind_bearing: 25.7    temperature: 14.7    templow: 3.3    wind_speed: 8.3    precipitation: 0  - condition: cloudy    datetime: '2023-05-13T07:00:00+00:00'    wind_bearing: 297.8    temperature: 16.8    templow: 4.4    wind_speed: 11.2    precipitation: 0attribution: >-  Weather forecast from met.no, delivered by the Norwegian Meteorological  Institute.friendly_name: Forecast gHome ```


### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

### Anything else?

![IMG_0246](https://user-images.githubusercontent.com/25884715/236703140-62dda100-d76c-467a-824e-c5c2f07586dd.jpeg)
![IMG_0245](https://user-images.githubusercontent.com/25884715/236703146-354db47d-07d5-407b-b5d4-742c8e1d3ddf.jpeg)
![IMG_0244](https://user-images.githubusercontent.com/25884715/236703147-d7a609ba-ea6d-4109-93e9-9442c1f0a6dc.jpeg)
