### ISSUE TITLE
[Bug]: Missing translation

### ISSUE THREAD

**Issue by dolenec** [piitaya/lovelace-mushroom#1138]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

The problem is that 1 specific string is not translated. In case that LED light is OFF then there in neverless of choosen GUI language there is text "off", but this text should be translatable.

and so on..

Picture of missing translation (marked with red color):
![image](https://user-images.githubusercontent.com/16633222/236852442-d31aaaf5-211c-49e6-8f07-164992d0d8b6.png)

### Expected Behavior

In **English** language should be:
Off
**German**:
Aus
**Italian**:
Spento
**Slovenian**:
Izklopljeno

and so on..

### Steps To Reproduce

Simply use my code in lovelace UI, and use own light entity.

### Context

YAML state
```
entities:
  - type: custom:mushroom-light-card
    entity: light.shelly_rgbw2_kuhinja1
    icon_color: grey
    show_brightness_control: true
    use_light_color: false
    show_color_control: false
    show_color_temp_control: false
    double_tap_action:
      action: more-info
    hold_action:
      action: more-info
    layout: horizontal
    fill_container: false
show_header_toggle: false
type: entities

```

### Environment

```markdown
- Browser: All (Firefox, Chrome, Phone browser)
- HA Version: 2023.5.2
- Mushroom: (up-to-date)
```
