### ISSUE TITLE
[Bug]: (chips card) Tap action on second chip follows previous one

### ISSUE THREAD

**Issue by Dixet** [piitaya/lovelace-mushroom#1144]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have a chips card with two template-chips inside. When I change the tap-action for the first of those chips to "navigate", the second chip will follow this behaviour and try to navigate. This results in an error because no navigation path is entered for this second chip. 

This behaviour does not occur for the entity-chip (not tested with other types), or when the second template-chip has the navigate-action and the first one does not 
<img width="215" alt="Schermafbeelding 2023-05-12 084048" src="https://github.com/piitaya/lovelace-mushroom/assets/8961696/ed3bd2b4-c818-4096-8639-02f2593eb167">

### Expected Behavior

When the second template-chip has the default on-tap action (i.e. no tap-action defined in yaml) it should show the default action, in my case the history chart

### Steps To Reproduce
Create a mushroom chips card with at least two chips of type "entity". Give the first one the on-tap action "navigate" and leave the second one deault
```yaml
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: sensor.philips_hue_motion_sensor_woonkamer_temperature
    name: Temp
  - type: entity
    entity: sensor.philips_hue_motion_sensor_woonkamer_illuminance_lux
    name: Licht
  - type: template
    icon: mdi:home-lightning-bolt-outline
    content: '{{ states(''sensor.energieverbruik_dagelijks'' )|round(1)}} kWh'
    entity: sensor.energieverbruik_dagelijks
    tap_action:
      action: navigate
      navigation_path: /dashboard-energieverbruik
  - type: template
    content: '{{ states(''sensor.huawei_omvormer_yield_today'' )|round(1)}} kWh'
    icon: mdi:solar-power-variant
```

### Context

YAML state
```yaml

```

### Environment

```markdown
- HA Version: 2023.5.2
- Mushroom: 2.7.1
```
