### ISSUE TITLE
[Bug]: Frequently, "Custom element doesn't exist: mushroom-title-card."

### ISSUE THREAD

**Issue by vangorra** [piitaya/lovelace-mushroom#1161]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

This is an oddly specific issue. In Chromium, mushroom cards inside a picture-elements card are frequently don't exist when an auto-entities card is on the dashboard before the picture-elements card. When this happens the text `Custom element doesn't exist: mushroom-title-card.` is in the place where the mushroom element should be.

### Expected Behavior

The mushroom card should always be visible.

### Steps To Reproduce

1. Add the dashboard from the yaml provided below.
2. In chrome, refresh the page.
  - The title card with text "Occasionally Visible" is not visible every ~5 refreshes.
  - The warehouse icon is always visible.
4. Change the order of elements so the auto-entites card is after the picture-elements card.
5. Refresh the page numerous times.
  - The title card is always visible.
  - The warehouse icon is always visible.

JS console does not show any errors or warnings different when the issue occurs or when it doesn't.

### Context

Dashboard with the issue:
```yaml
title: Home
views:
  - path: default_view
    panel: false
    title: Visibility Test
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: binary_sensor.front_door
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1em'
            title: Occasionally Visible
          - type: icon
            icon: mdi:warehouse
            title: Always Visible
            style:
              transform: translate(0px, 0px)
              right: 1em
              top: 1em


```

### Environment

```markdown
- Browser: Chromium 114.0.5735.90 (Official Build) (64-bit) but all chromium version is impacted.
- HA Version: 2023.5.4 but all versions in the last few months are impacted.
- Mushroom: 2.7.1 but all versions in the last few months are impacted.
```

### Anything else?

Video demonstration of the issue:
[Screencast from 2023-06-09 12-53-06.webm](https://github.com/piitaya/lovelace-mushroom/assets/1752370/ad87bec6-c570-4b6f-97ef-ca2da232b4c0)

**Comment by lennon101** [comment]
@vangorra I'm not a developer but out of shear interest I tried to replicate this and was unable to. My yaml for this dashboard looks like the below. I have refreashed the page about 20 times now and the "Occasionally Visible" title has never disappeared. Food for thought. 

```
  - title: test
    path: test
    badges: []
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: binary_sensor.fridge
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1em'
            title: Occasionally Visible
          - type: icon
            icon: mdi:warehouse
            title: Always Visible
            style:
              transform: translate(0px, 0px)
              right: 1em
              top: 1em
```

**Environment:**

```
Chrome: Version 114.0.5735.134 (Official Build) (64-bit) 
HA: Home Assistant 2023.5.2 Frontend 20230503.3 - latest
Mushroom: v2.7.1
```

**Comment by alephtaph** [comment]
Same issue here since I updated today to 2023.6.2
None of the mushroom cards are displayed. Config didn't change for at least a month.

**Comment by piitaya** [comment]
Did you try this ? 
1. delete mushroom resources (https://my.home-assistant.io/redirect/lovelace_resources/)
2. uninstall Mushroom from HACS
3. reinstall Mushroom from HACS

**Comment by vangorra** [comment]
Investigating this a bit further, will reopen when only I'm certain it's an issue with mushroom card but going to log the investigation here anyway.

## Frequency of issue:
- In firefox - Almost never.
- In chrome/chromium desktop - Roughly every 8 refreshes.
- In HA app (which is chromium) - Roughly every 8 refreshes.
- While dashboard is in edit mode - Never.

## Observations
- Reinstalling, clearing, cache, etc - Has no effect.
- Occurs when the following conditions are met:
  - A `custom:` card is used. After the `custom:` card, a `picture-elements` with mushroom cards elements is used. The mushroom cards in the picture elements card will be occasionally visible.
  -  Note: If your picture-elements card (with mushroom card elements) is not preceded by any `custom:` card, it is always visible. See example.
```yaml
title: House
views:
  - icon: mdi:home
    panel: false
    path: default_view
    title: Home
    badges: []
    cards:
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Always Visible 1
      - type: custom:auto-entities
        card:
          type: entities
          show_empty: false
          state_color: true
        filter:
          include:
            - attributes:
                device_class: door
              state: 'on'
        show_empty: false
        sort:
          method: name
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Always Visible 2
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Occasionally Visible 1
  ```
- Mushroom cards that fail to appear are replaced with a non-visible error card with error `Custom element doesn't exist: mushroom-chips-card.`.
  ![image](https://github.com/piitaya/lovelace-mushroom/assets/1752370/ab20155f-c0e1-4dc0-b916-76421115ad46)
- When loading a more complex dashboard (mushroom cards with state), a console error is often present when a mushroom card does not appear. The exception is thrown by mushroom when closing a connection. This appears to be a symptom of the problem, not the cause.
  ![image](https://github.com/piitaya/lovelace-mushroom/assets/1752370/3365f900-4e95-4753-b355-7b135040e13d)
