### ISSUE TITLE
[Bug]: icon color won't work

### ISSUE THREAD

**Issue by platini76** [piitaya/lovelace-mushroom#1166]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

on this card, there is no possibility to have a state icon change on is_state

### Context

YAML state
```yaml
type: custom:mushroom-entity-card
entity: sensor.number_of_lights_on
icon: mdi:home-lightbulb-outline
icon_color: |-
  {% if is_state('sensor.number_of_lights_on', '1') %}
    orange
  {% endif %}
tap_action:
  action: call-service
  service: light.turn_off
  target:
    area_id:
      - bagno_master
      - camera_master
      - cucina
      - esterno
      - lavanderia
      - piano_sotto
      - soggiorno
      - soppalco
  data: {}
```

### Environment

```markdown
- Browser: chrome
- HA Version: 2023.6
- Mushroom: last
```
