### ISSUE TITLE
[Bug]: Assist action does not work

### ISSUE THREAD

**Issue by dnestico** [piitaya/lovelace-mushroom#1194]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When you set the tap action as "Assist" it doesn't work and it also throws an error in the editor UI.

<img width="1078" alt="Screenshot 2023-07-06 at 7 44 02 PM" src="https://github.com/piitaya/lovelace-mushroom/assets/3034555/a8ed1433-9f88-4432-88a6-c759471a7620">

### Expected Behavior

Assist tap action should open assist popup.

### Steps To Reproduce

1. Set any entity (sun.sun)
2.  Change tap action to "Assist"
3. Editor breaks and tap action doesn't work

https://github.com/piitaya/lovelace-mushroom/pull/1173

### Context

YAML state
```yaml
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: sun.sun
    tap_action:
      action: assist
    icon: mdi:message-text
    icon_color: blue
    name: Assist
    content_info: name
```

### Environment

```markdown
- Browser: Arc Browser (chromium)
- HA Version: 2023.7
- Mushroom: 3.0.0
```
