### ISSUE TITLE
[Bug]: chips take whole line

### ISSUE THREAD

**Issue by martindybal** [piitaya/lovelace-mushroom#1197]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I need to display multiple chips and some of them only when some condition is true. I tried using `entity-filter` which works fine. But it displays the chips on two lines instead of one.

<img width="1208" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/7644099/5b39db68-8aeb-45c4-ba71-d2a789371c7f">

### Context

YAML state
```yaml
    badges:
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: sensor.realtemperature_104_sitting_room_temperature_and_humidity_sensor
          - type: entity
            entity: sensor.humidity_104_sitting_room_temperature_and_humidity_sensor

      - type: entity-filter
        entities:
          - entity: binary_sensor.reedcontact_104_door
            type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: binary_sensor.reedcontact_104_door
                use_entity_picture: false
                content_info: name
        state_filter:
          - "on"
```

### Environment

```markdown
- Browser: https://whatismybrowser.com/w/ZZL5FMZ
- HA Version:
Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest
- Mushroom: v3.0.0
```

**Comment by piitaya** [comment]
Each chip card use one line. You define 2 chips card so you get 2 lines.
To solve your issue, you can use conditional chip to add display condition for some chips within the same chip line.

**Comment by martindybal** [comment]
Thanks. I got it. FOr next generation

```yaml
    badges:
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: sensor.realtemperature_104_sitting_room_temperature_and_humidity_sensor
          - type: entity
            entity: sensor.humidity_104_sitting_room_temperature_and_humidity_sensor
          - type: conditional
            conditions:
              - entity: binary_sensor.reedcontact_104_door
                state: "on"
            chip:
              entity: binary_sensor.reedcontact_104_door
              type: template
              content: Dveře
              icon: mdi:door-sliding-open
              tap_action:
                action: more-info
          - type: conditional
            conditions:
              - entity: binary_sensor.reedcontact_104_balcony_door
                state: "on"
            chip:
              entity: binary_sensor.reedcontact_104_balcony_door
              type: template
              content: Balkonové dveře
              icon: mdi:door
              tap_action:
                action: more-info
          - type: conditional
            conditions:
              - entity: binary_sensor.reedcontact_104_balcony_handle
                state: "on"
              - entity: binary_sensor.reedcontact_104_balcony_door
                state: "off"
            chip:
              entity: binary_sensor.reedcontact_104_balcony_handle
              type: template
              content: Klika
              icon: mdi:hand-back-left
              tap_action:
                action: more-info
          - type: conditional
            conditions:
              - entity: binary_sensor.reedcontact_104_hs_portal
                state: "on"
            chip:
              entity: binary_sensor.reedcontact_104_hs_portal
              type: template
              content: HS
              icon: mdi:application-outline
              tap_action:
                action: more-info
          - type: conditional
            conditions:
              - entity: binary_sensor.reedcontact_104_window
                state: "on"
            chip:
              entity: binary_sensor.reedcontact_104_window
              type: template
              content: Okno
              icon: mdi:window-open-variant
              tap_action:
                action: more-info
          - type: conditional
            conditions:
              - entity: binary_sensor.reedcontact_104_window_ventilation
                state: "on"
              - entity: binary_sensor.reedcontact_104_window
                state: "off"
            chip:
              entity: binary_sensor.reedcontact_104_window_ventilation
              type: template
              content: Okno ventilace
              icon: mdi:fireplace-off
              tap_action:
                action: more-info
```
