### ISSUE TITLE
[Bug]: Click event on mushroom button in popup does not work

### ISSUE THREAD

**Issue by tmilz** [piitaya/lovelace-mushroom#1212]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Clicking the mushroom button in a popup map no longer works.
Here is a code example:
```
type: button
name: Popup
show_name: true
show_icon: true
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      deviceID: this
      content:
        type: vertical-stack
        cards:
          - type: custom:mushroom-entity-card
            entity: input_boolean.toggle_test
```
The code runs with version Mushroom version 2.8.1.
It does not work with newer versions.
The used popup module is browser_mod 2.2.2

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Google Chrome
- HA Version: 2023.7.1
- Mushroom: 3.0.3
```
