### ISSUE TITLE
[Bug]: mushroom cards dont work in popup-card

### ISSUE THREAD

**Issue by fxxer** [piitaya/lovelace-mushroom#1218]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I don't now the exact version when it stopped working. I am using custom:popup-card (browser_mod integration https://github.com/thomasloven/hass-browser_mod ) where using custom:auto-entities I am generating list of lights that are on. Clicking on light tu turn on / off stopped working (also mushroom entity card in other popups-cards). Other buttons or entities not using mushroom cards are working properly.

### Expected Behavior

Clicking on mushroom entity should do default action / toggle entity state also in custom:popup-card

### Steps To Reproduce

1. My versions:
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Mushroom v3.0.5
browser_mod 2.3.0

2. try the card I coppied in "Context"
3. I can't use mushroom buttons in popups

### Context

Here's the card for example
```yaml
type: custom:popup-card
entity: switch.template_lights
title: All Lights
dismissable: true
card:
  cards:
    - type: custom:mushroom-light-card
      entity: switch.template_lights
    - type: custom:auto-entities
      filter:
        exclude:
          - domain: automation
          - entity_id: group.all_lights
          - entity_id: '*_1*'
          - entity_id: '*_2*'
          - entity_id: '*_3*'
          - entity_id: '*_4*'
          - entity_id: '*_5*'
          - entity_id: light.presence_simulation
        include:
          - domain: light
            attributes:
              supported_features: '>= 44'
            options:
              type: custom:mushroom-light-card
              show_brightness_control: true
              use_light_color: true
              show_color_temp_control: true
              show_color_control: true
              collapsible_controls: true
              layout: horizontal
            state: 'on'
          - domain: light
            attributes:
              supported_features: < 44
            options:
              type: custom:mushroom-light-card
              show_brightness_control: true
              use_light_color: true
              show_color_temp_control: true
              show_color_control: false
              collapsible_controls: true
              layout: horizontal
            state: 'on'
          - entity_id: switch.*_light*
            state: 'on'
            options:
              type: custom:mushroom-light-card
              show_brightness_control: false
              use_light_color: true
              show_color_temp_control: false
              show_color_control: false
              collapsible_controls: true
              layout: horizontal
      show_empty: false
      card:
        square: false
        columns: 1
        type: grid
      card_param: cards
      sort:
        method: last_changed
        reverse: true
        numeric: false
  type: vertical-stack
```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.7.2
- Mushroom: 3.0.5
```
