### ISSUE TITLE
[Bug]: Slider does not change entity value when clicked

### ISSUE THREAD

**Issue by bzumik1** [piitaya/lovelace-mushroom#1227]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When I click on the slider the entity value does not change, the value only changes when I drag over the slider.

**Click:**
<img width="543" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/32042186/3d4a8aee-7196-4c52-8a46-7f309ac96a88">
**Drag:**
<img width="543" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/32042186/3d4a8aee-7196-4c52-8a46-7f309ac96a88">

### Expected Behavior

Change entity value when I click on slider.

### Context

YAML state
```yaml
square: false
type: grid
cards:
  - type: custom:mushroom-title-card
    title: Nastavení
  - type: custom:mushroom-number-card
    entity: input_number.teplota_svetla
  - type: custom:mushroom-number-card
    entity: input_number.jas_svetla
columns: 1
```

### Environment

```markdown
- Browser: Safari
- HA Version: 2023.8.1
- Mushroom: 3.0.5
```
