### ISSUE TITLE
[Feature]: Chip with motion sensor including relative last change

### ISSUE THREAD

**Issue by afarago** [piitaya/lovelace-mushroom#1261]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

No, it is a visual improvement.

### Describe the solution you'd like

I would like a chip that displays icon according to motion and adds the last update relative time and updates it regularly.

![image](https://github.com/piitaya/lovelace-mushroom/assets/4489389/1a7db018-5f34-4d1c-9433-c9fcddf31a5b)

### Describe alternatives you've considered

I have worked around with a template chip. yet it fails to update the relative time regularly (only at state change).

``` yaml
        type: custom:mushroom-chips-card
        chips:
          - type: template
            entity: "[[[ return variables.motion ]]]"
            icon: |-
              [[[ 
                return states[variables.motion]=='on' ? 'mdi:motion-sensor' : 'mdi:motion-sensor-off' 
              ]]]
            content: |-
              [[[
                return "{{(states['"+variables.motion+"'].last_changed | relative_time ~ ' ago') if not is_state('"+variables.motion+"','unavailable') else 'unavailable'}}";
              ]]]
            tap_action:
              action: more-info
```

**Comment by piitaya** [comment]
Is this code working for you? You can use entity chip
```yaml
- type: entity
  entity: binary_sensor.motion
  content_info: last-changed
```
