### ISSUE TITLE
Neither content nor content_info are documented anywhere

### ISSUE THREAD

**Issue by salvisbh** [piitaya/lovelace-mushroom#1273]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Especially in combination with auto-entities the use of the functionally ingenious mushroom-cards is very difficult without studying the source-code in detail or without assembling examples from various Google-searches. This concerns especially the two attributes
- content
- content_info
In addition, these two elements are used differently depending on the card type or do not exist at all depending on the type. For example, in chips content_info must be used, while in other types only content must be defined.
It would be extremely helpful to include these two elements in the documentation. 

### Expected Behavior

- content and
- content-info
should be documented and their meaning described.

### Context

YAML state
```yaml
- type: custom:mushroom-chips-card
    chips:
      - type: light
        entity: light.arbeiten
        content_info: none
      - type: template
        entity: binary_sensor
        content: Garage Door
```

### Environment

```markdown
- Browser: Brave 1.59.120 (Chromium 118)
- HA Version: 2023.10.4
- Mushroom: v3.1.0
```
