### ISSUE TITLE
[Bug]: Conditional Chip condition seleciton dropdown in UI renders an empty dropdown 

### ISSUE THREAD

**Issue by lennon101** [piitaya/lovelace-mushroom#1279]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

This seems to be an issue that has occured with the latest update of mushroom `v3.2.0` as the conditional chips were working yesterday before I updated to HA `2023.11.0`.  

I've tried with multiple entity types and tried building a new card from scratch and its the same issue. Problem occurs in both light and dark mode. The best way to describe this building (in my opinion) is with a photo. See screenshot below: 

![image](https://github.com/piitaya/lovelace-mushroom/assets/1709944/30938f5c-a872-4d66-8d0d-e45e6bb97eb7)

### Expected Behavior

Upon selecting the dropdown menu, I should be presented with the `state is equal to` or `the state is not equal to` options

### Context

YAML state
```
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: ''
    subtitle: LAUNDRY DASHBOARD
  - type: custom:mushroom-chips-card
    chips:
      - type: conditional
        conditions:
          - entity: sensor.laundry_twin_socket_power
            state_not: '0.0'
        chip:
          type: entity
          entity: sensor.laundry_twin_socket_power
          tap_action:
            action: more-info
```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.11.0
- Mushroom: v3.2.0
```
