### ISSUE TITLE
[Feature]: Add a chip line in mushroom template card

### ISSUE THREAD

**Issue by BBESINET** [piitaya/lovelace-mushroom#1286]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

In order to build more customized mushroom card, many usage require to have additional buttons.

One very interresting option to have these buttons is to have a row of Chips, as they already integrate many customisation option and are coherent in term of appearance.

### Describe the solution you'd like

I would like to have an optional rom of chip:
- inside the template card
- placed verticaly or horizontaly (to the user choice) 
- following the template card format (default, vertical or horizontal) 
- positionned to the user choice (top, bottom, right, left).

### Describe alternatives you've considered

Stack-in of template card + chip is the option I use (like many others), but is not always obvious, needs YAML input and is not as versatile as if it was embedded.

### Additional context

Some ideas comming from here to show what it could look like for room cards:
https://github.com/piitaya/lovelace-mushroom/issues/55

![image](https://github.com/piitaya/lovelace-mushroom/assets/115801091/cb860d1e-57f8-4211-b589-3c2a3fdab214)

![image](https://github.com/piitaya/lovelace-mushroom/assets/115801091/fdfc7000-4080-4225-949a-756b8b805465)

![image](https://github.com/piitaya/lovelace-mushroom/assets/115801091/9d48db23-0320-4545-bcdf-11eb96412403)

**Comment by bdsoha** [comment]
It would be great if there was an **`action`** section for templates cards.
I have accomplished something similar using the following:

```yaml
  type: grid
  columns: 2
  square: false
  cards:
    - type: custom:mushroom-entity-card
      entity: binary_sensor.****
      icon_color: red
      name: ****
      tap_action:
        action: none
      hold_action:
        action: none
      double_tap_action:
        action: none
    - type: custom:paper-buttons-row
      styles:
        justify-content: flex-end
      base_config:
        preset: mushroom
        styles:
          button:
            margin-top: 12px
            margin-right: 12px
      buttons:
        - icon: mdi:refresh
          entity_id: ****
          tap_action:
            action: toggle
```
