### ISSUE TITLE
[Bug]: Mushroom Select Card - no scroll bar when option list is too long

### ISSUE THREAD

**Issue by mrombouts** [piitaya/lovelace-mushroom#1287]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When a Select card with 7 options is shown in a pop-up window, not all options are displayed - see the screenshot:
![image](https://github.com/piitaya/lovelace-mushroom/assets/68616858/0465557c-120f-4b53-8b4e-60f17052037e)

Some issues at the end of the drop-down list are not displayed
Not sure if this is an issue with mushroom card or with the pop-up card

### Expected Behavior

A scroll bar next to the selection list when the pop-up window is too small to show the entire list

### Steps To Reproduce

1. Create a pop-up card with a long mushroom - select card
2. Open the select card - not all values are seen

### Context

YAML state - the yaml code of the pop-up window
```
type: custom:popup-card
entity: climate.airco_bureau
title: Airco Bureau
dismissable: true
card:
  type: custom:vertical-stack-in-card
  cards:
    - type: horizontal-stack
      cards:
        - type: custom:mushroom-template-card
          primary: Koelen
          icon: mdi:snowflake
          entity: climate.airco_bureau
          layout: vertical
          icon_color: |
            {% if states('climate.airco_bureau') == 'cool' %}
            blue
            {% endif %}
          tap_action:
            action: call-service
            service: climate.set_hvac_mode
            target:
              entity_id: climate.airco_bureau
            data:
              hvac_mode: cool
        - type: custom:mushroom-template-card
          primary: Verwarmen
          icon: mdi:fire
          entity: climate.airco_bureau
          layout: vertical
          icon_color: |
            {% if states('climate.airco_bureau') == 'heat' %}
            red
            {% endif %}
          tap_action:
            action: call-service
            service: climate.set_hvac_mode
            target:
              entity_id: climate.airco_bureau
            data:
              hvac_mode: heat
        - type: custom:mushroom-template-card
          primary: Drogen
          icon: mdi:water-percent
          entity: climate.airco_bureau
          layout: vertical
          icon_color: |
            {% if states('climate.airco_bureau') == 'dry' %}
            amber
            {% endif %}
          tap_action:
            action: call-service
            service: climate.set_hvac_mode
            target:
              entity_id: climate.airco_bureau
            data:
              hvac_mode: dry
        - type: custom:mushroom-template-card
          primary: Uit
          icon: |
            {% if states('climate.airco_bureau') != 'off' %}
            mdi:power-on
            {% else %}
            mdi:power-off
            {% endif %}  
          entity: climate.airco_bureau
          layout: vertical
          icon_color: |
            {% if states('climate.airco_bureau') != 'off' %}
            yellow
            {% else %}
            green
            {% endif %}
          tap_action:
            action: call-service
            service: climate.set_hvac_mode
            target:
              entity_id: climate.airco_bureau
            data:
              hvac_mode: 'off'
    - type: horizontal-stack
      cards:
        - type: conditional
          conditions:
            - entity: climate.airco_bureau
              state: cool
          card:
            type: custom:numberbox-card
            border: false
            entity: input_number.airco_bureau_cool_temp
            name: 'Temperatuur: '
            icon_plus: mdi:chevron-up
            icon_minus: mdi:chevron-down
            unit: °C
        - type: conditional
          conditions:
            - entity: climate.airco_bureau
              state: heat
          card:
            type: custom:numberbox-card
            border: false
            entity: input_number.airco_bureau_heat_temp
            name: 'Temperatuur: '
            icon_plus: mdi:chevron-up
            icon_minus: mdi:chevron-down
            unit: °C
    - type: conditional
      conditions:
        - condition: state
          entity: climate.airco_bureau
          state_not: 'off'
      card:
        type: custom:mushroom-select-card
        entity: input_select.airco_bureau_fan
        name: Ventilator
        icon: mdi:fan
        layout: horizontal
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
        secondary_info: none
    - type: conditional
      conditions:
        - condition: state
          entity: climate.airco_bureau
          state_not: 'off'
      card:
        type: custom:mushroom-select-card
        entity: input_select.airco_bureau_horizontal_swing
        name: Airflow Horizontaal
        icon: mdi:fan
        layout: horizontal
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
        secondary_info: none
    - type: conditional
      conditions:
        - condition: state
          entity: climate.airco_bureau
          state_not: 'off'
      card:
        type: custom:mushroom-select-card
        entity: input_select.airco_bureau_vertical_swing
        icon: mdi:fan
        layout: horizontal
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
        secondary_info: none
        name: Airflow Verticaal
size: ''

```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.11.0
- Mushroom: 3.2.2
```
