### ISSUE TITLE
[Bug]: <Person picture not show correctly>

### ISSUE THREAD

**Issue by gianniocchipinti** [piitaya/lovelace-mushroom#1304]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

![image](https://github.com/piitaya/lovelace-mushroom/assets/46269269/409adaab-29ba-4894-a02b-773d65098b1f)

Hi everyone, it often happens that the image of the person entity is not displayed correctly.

You can try to demure it by clicking on it, enabling an action for example.

It can be resolved by reloading the page.

I have latest version of mushroom theme

Thank you

### Steps To Reproduce

Click card

### Context

YAML state
```
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: person.myname
    use_entity_picture: true
```

### Environment

```markdown
- Browser: Chrome

- HA Version:
Core 2023.11.3
Supervisor 2023.11.6
Operating System 11.1
Frontend 20231030.2

- Mushroom Themes: 0.0.9
```
