### ISSUE TITLE
[Feature]: Button card

### ISSUE THREAD

**Issue by martindybal** [piitaya/lovelace-mushroom#1324]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I'd like to be able to use `<mushroom-button>` separately. It would be useful for various actions on my dashboard. In my scenario, I use components to navigate to the dashboard of each component. Currently I can't use a single button style

<img width="383" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/7644099/dd9790ba-25f9-4442-a330-17fc590a16f5">

```yaml
square: true
type: grid
columns: 4
cards:
  - type: custom:vertical-stack-in-card
    cards:
      - type: custom:mushroom-light-card
        entity: light.103_office_biodynamic_light
        layout: vertical
        name: Světla
        fill_container: true
        secondary_info: none
        tap_action:
          action: navigate
          navigation_path: /lovelace-lights/dashboard
      - type: custom:mushroom-entity-card
        icon: mdi:lightbulb-group-off-outline
        entity: button.press_104_sitting_room_switch_light
        layout: vertical
        secondary_info: none
        tap_action:
          action: call-service
          service: light.turn_off
          target:
            entity_id: light.103_office_biodynamic_light
        primary_info: none
        icon_color: black
  - type: custom:mushroom-cover-card
    entity: cover.all
    fill_container: true
    layout: vertical
    secondary_info: none
    name: Stínění
    show_buttons_control: true
    tap_action:
      action: navigate
      navigation_path: /lovelace-shades/dashboard
  - type: custom:vertical-stack-in-card
    cards:
      - type: custom:mushroom-fan-card
        entity: fan.pichler
        fill_container: true
        layout: vertical
        secondary_info: none
        icon_animation: true
        name: Větrání
        tap_action:
          action: navigate
          navigation_path: /lovelace-ventilation/dashboard
      - type: custom:mushroom-entity-card
        entity: select.pichler_mode
        icon_color: black
        secondary_info: none
        primary_info: none
        layout: horizontal
  - type: custom:mushroom-lock-card
    fill_container: true
    secondary_info: none
    layout: vertical
    name: Zámky
    hold_action:
      action: navigate
      navigation_path: /lovelace-security/dashboard
    entity: lock.locks
```

### Describe the solution you'd like

Custom card 

```yaml
      - type: custom:mushroom-button
        icon: mdi:lightbulb-group-off-outline
        tap_action:
          action: call-service
          service: light.turn_off
          target:
            entity_id: light.all
        icon_color: black
```
