### ISSUE TITLE
[Feature]: Allow hide Open button on lock card

### ISSUE THREAD

**Issue by martindybal** [piitaya/lovelace-mushroom#1325]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

partly related to https://github.com/piitaya/lovelace-mushroom/issues/777 and https://github.com/piitaya/lovelace-mushroom/issues/1311

Add the hide option to open the door. My lock supports open doors. Several times I have opened a door by mistake and it cannot be closed. 

### Describe the solution you'd like

```yaml
  - type: custom:mushroom-lock-card
    entity: lock.main_door
    ShowOpenDoorButton: false
```
