### ISSUE TITLE
[Feature]: Title card... in case of no subtitle do not use the space for it

### ISSUE THREAD

**Issue by RkcCorian** [piitaya/lovelace-mushroom#1345]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I would like to use the title car for navigation but only the title without subtitle. But it still takes the space for it which looks ugly

### Describe the solution you'd like

In case no subtitle is given reduce the spacing so that it looks like in the standard cards when using a vertical stack and giving a title. Perfect would be even when there is a possibility to defined the space below the title and the bottom of the card

### Additional context
![image](https://github.com/piitaya/lovelace-mushroom/assets/79741077/8d3938fb-32e6-4491-b774-696190a6dd2f)

_No response_

**Comment by RkcCorian** [comment]
@piitaya : Many thanks for the change but it is not ready yet, please reopen the ticket.
Reason: There is still too much space between titel and the card boundary when giving only a title and NO subtitle. It looks then odd on the dashboard

Currently (by giving only the titel, NO subtitle)
![image](https://github.com/piitaya/lovelace-mushroom/assets/79741077/73187863-dc7a-4c35-9829-de01a0972615)

```
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: Hello, {{ user }}  Test Heading!
    title_tap_action:
      action: navigate
      navigation_path: /dashboard-test/sicherheit
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-entity-card
        entity: input_button.stimmung_gemutlich
        name: Gemütliche Stimmung
        fill_container: false
        secondary_info: none
        tap_action:
          action: more-info
        double_tap_action:
          action: toggle
      - type: custom:mushroom-entity-card
        entity: input_button.stimmung_weihnachten
        name: Starte Weihnachten
        fill_container: false
        secondary_info: none
        tap_action:
          action: more-info
        double_tap_action:
          action: toggle
```

Expected (like any other standard card (vertical-stack with title given)
![image](https://github.com/piitaya/lovelace-mushroom/assets/79741077/986ed7e4-2b20-47b3-88f4-4af420ded7d0)

```
type: vertical-stack
title: Energie & Leistung
cards:
  - type: entities
    entities:
      - entity: sensor.ecu_today_energy
      - entity: sensor.ecu_current_power
```
