### ISSUE TITLE
[Bug]: HVAC Modes icons not visible any longer after upgrade

### ISSUE THREAD

**Issue by ziolelle** [piitaya/lovelace-mushroom#1351]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

After having upgraded Mushroom to 3.4.0, now the icons for the HVAC modes selected for the climate entities are not visible any longer
<img width="526" alt="image" src="https://github.com/piitaya/lovelace-mushroom/assets/24245403/a56525df-be76-43ae-b30d-57784c78e387">
The issue is present with or without the "Temperature control" switch enabled

### Expected Behavior

before version 3.4.0 HVAC modes icons were perfectly visible

### Steps To Reproduce

Add to a page a mushroom-climate-card and in the properties select the HVAC modes to be visible.

### Context

YAML state
```yaml
  - type: custom:mushroom-climate-card
    entity: climate.mitsubishi_msz_hr25vf
    hvac_modes:
      - 'off'
      - cool
      - heat
    show_temperature_control: false
```

### Environment

```markdown
- Browser: Chrome, Safari, iOS HA App
- HA Version: 2024.1.6
- Mushroom: 3.4.0
```
