### ISSUE TITLE
Improve light card - Hide brightness slider when light is only On/Off

### ISSUE THREAD

**Issue by zbuh** [piitaya/lovelace-mushroom#136]
**Is your feature request related to a problem? Please describe.**
In the example bellow, all light cards will have slider for brightness event when the light is only able to On/Off.
In RGB lights this is already done, the control is only shown when light has RGB capability

**Describe the solution you'd like**
The card should discover light capabilities, and show controls accordingly. Currently is already done for RGB control.

**Describe alternatives you've considered**
n/a

**Additional context**
```
      - type: custom:auto-entities
        card:
          type: grid
          columns: 2
          square: false
        card_param: cards

        filter:
          include:
            - group: group.all_lights
              state: "on"
              options:
                type: custom:mushroom-light-card
                show_brightness_control: true
                use_light_color: true
                show_color_control: true
                hide_state: true
```
![image](https://user-images.githubusercontent.com/190734/154661578-5ac507be-8040-4b54-b958-8045f8a85741.png)
