### ISSUE TITLE
double_tap_action and hold_action not working in Template chips

### ISSUE THREAD

**Issue by antonio1475** [piitaya/lovelace-mushroom#137]
**Describe the bug**
double_tap_action and hold_action don't work in Template chips, even though they are set through the UI.
Tap action works fine

**To Reproduce**
```
type: template
content: >-
  {{ states("switch.lavadora_local") | title }} ({{
  state_attr("switch.lavadora_local", "current_consumption") }} W)
icon: mdi:power-socket-de
tap_action:
  action: call-service
  service: switch.toggle
  service_data: {}
  target:
    device_id: xxxx
icon_color: |
  {{"red" if is_state("switch.lavadora_local","on")}}
hold_action:
  action: call-service
  service: light.toggle
  service_data: {}
  target:
    entity_id: light.ordenador
double_tap_action:
  action: call-service
  service: light.turn_off
  service_data: {}
  target:
    entity_id: light.ordenador

```

I've tried simpler combinations (one action only) and it's the same thing.

**Expected behavior**
Double tap and hold actions to work on template chips, as the UI suggests.

**Additional context**
1.0.6 added actions to ¿all? cards.
