### ISSUE TITLE
[Bug]: Wallpanel

### ISSUE THREAD

**Issue by w1tw0lf** [piitaya/lovelace-mushroom#1373]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Using wallpanel(https://github.com/j-a-n/lovelace-wallpanel) to display info on a static sceen. When adding any type of mushroom card, the memory usage slowly increases and browser eventialy crashes, with a "aww snap" error.

### Expected Behavior

Used to work perfectly for the past year.

### Steps To Reproduce

RPi 4 loads chrome and displays a dashboard dedicated to wallpanel setup.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: chrome
- HA Version: 2024.2.1
- Mushroom: 3.4.2
```

### Anything else?

more info here as well: https://github.com/j-a-n/lovelace-wallpanel/issues/205
Setting up the same layout as on the wallpanel on normal dashboard, works perfectly.

**Comment by Pscharumbel** [comment]
Similar with me. I use Wallpanel with Mushroom Cards on an LG TV. After about 90 minutes, the browser crashes with the message 'Out of memory.' This wasn't a problem with the old version.

**Comment by w1tw0lf** [comment]
Just to add, if I configure it without any mushroom cards, it works perfectly.

**Comment by swampylee** [comment]
I have this too - latest Mushroom with latest HA and latest Wallpanel - refreshes are really slow, card updates significantly delayed and it seems directly related to Mushroom cards use.

**Comment by piitaya** [comment]
Can you share your dashboard configuration with Mushroom card?

**Comment by w1tw0lf** [comment]
I did this as a test, to see 
```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  keep_screen_on_time: 0
  black_screen_after_time: 0
  image_url: media-entity://camera.google_photos_photo_frame_media
  show_image_info: false
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 457px
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-text-color': '#e1e1e1'
      '--secondary-text-color': '#9b9b9b'
  cards:
    - entity: light.main_bedroom_lamp_left
      type: custom:mushroom-light-card
      layout: vertical
      name: Bedlamp Left    
      wp_style:
        grid-column: 1 / 1
        grid-row: 1 / 1
        background-color: '#00000099'
    - type: custom:button-card
      color_type: blank-card
      wp_style:
        grid-column: 2 / 2
        grid-row: 1 / 1
    - type: custom:button-card
      color_type: blank-card
      wp_style:
        grid-column: 3 / 3
        grid-row: 1 / 1
    - entity: light.main_bedroom_lamp_right
      type: custom:mushroom-light-card
      layout: vertical
      name: Bedlamp Left       
      wp_style:
        grid-column: 4 / 4
        grid-row: 1 / 1
        background-color: '#00000099'
views:
  - title: Home
    type: custom:grid-layout
    layout:
      gridrows: auto
      grid-template-columns: 25% 25% 25% 25%
      grid-template-areas: |
        "c1 c2 c3 c4"
    badges: []
    cards: []
```
If you keep an eye on either task manager in chrome or native you will see the memory slowly increase and the crashes chrome.
