### ISSUE TITLE
An input_select card

### ISSUE THREAD

**Issue by fnoir** [piitaya/lovelace-mushroom#138]
It is necessary to make two actions for the input_select which is not very practical to use especially on a tablet.

```yaml
input_select:
  who_cooks:
    name: Who cooks today
    options:
      - Paulus
      - Anne Therese
    initial: Anne Therese
    icon: mdi:panda
```

![image](https://user-images.githubusercontent.com/35193356/154671874-4d0f67ce-40f8-40f0-98af-3f1a35a5d5dd.png)

![image](https://user-images.githubusercontent.com/35193356/154671954-ee2dd0d2-3941-470b-8662-0d32b2344c26.png)

To improve its use, it would be necessary to add the possibility of changing options directly from the card, such as a list of buttons like  shutters' card

![image](https://user-images.githubusercontent.com/35193356/154672338-ceb7fbc6-bf85-4fdf-b999-4ec84828fc39.png)
