### ISSUE TITLE
[Bug]: Unresponsive light status control

### ISSUE THREAD

**Issue by dreamwhite** [piitaya/lovelace-mushroom#1384]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Toggling the status of a light updates the card status after several seconds

### Expected Behavior

Toggling the status of a light should update the card status immediately (or at least within a few seconds)

### Steps To Reproduce

Entity card configuration

```yaml
type: custom:mushroom-entity-card
entity: switch.shelly_shsw_1_XXXXXXXXXXXX
fill_container: true
name: Ceiling
tap_action:
  action: toggle
icon: mdi:ceiling-light
```
![image](https://github.com/piitaya/lovelace-mushroom/assets/17933708/94ab9b6e-87bb-4f32-9e99-0c879e9a289c)

1. Light turned off
2. Click on the card (so it toggles the status on/off or viceversa)
3. The card reports that the light is still turned off despite being actually on. Several seconds (circa 30) pass before the card status is updated and correctly reports it.
 
If using the stock entities card

```yaml
type: entities
entities:
  - light.shelly_1_XXXXXXXX_XXXXXXXXXX
```

the bug disappears

### Environment

```markdown
- Browser: both Chrome and Firefox as well as the mobile app show the same problem
- HA Version: Core 2024.2.4 and Frontend  20240207.1  
- Mushroom: v3.4.2
```

### Anything else?

The same problem described here won't show up with a Xiaomi Mi Desk Lamp, which correctly reports the status immediately.

Many thanks in advance

dreamwhite
