### ISSUE TITLE
[Bug]: BrowserMod action: fire-dom-event removed from editor 

### ISSUE THREAD

**Issue by binarybucks** [piitaya/lovelace-mushroom#1392]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

When trying to add browser mod popups to existing cards, the added action and popup code sometimes gets removed in the code editor due to the unsupported tap_action. 

![image](https://github.com/piitaya/lovelace-mushroom/assets/782356/1919e37c-64ea-4a3c-a4f4-4fc5c75562c3)

According to https://github.com/piitaya/lovelace-mushroom/issues/490 `action: "fire-dom-event"` should be working in the code editor. 

### Expected Behavior

Code editor should not remove any code if some action is unknown 

### Steps To Reproduce

Create a new mushroom card e.g. entity-card and switch to code editor and add a tap_action with `action: fire-dom-event`  e.g. 
```
type: custom:mushroom-entity-card
entity: person.home
fill_container: true
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Popup example
      content:
        type: entities
        entities:
          - person.home 
```

The card saves correctly and the popup also works when saving the card. 

Open the card configuration again, switch to the code editor and change tap_action to e.g. hold_action. 
The code instantly changes to `action: '' ` and removes all other code for that action

![image](https://github.com/piitaya/lovelace-mushroom/assets/782356/1ec599c7-1d2c-4300-8f92-19e93d8587e5)

Copy/pasting the tap_action to other cards also only pastes `action: '' `

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Edge 122.0.2365.66
- HA Version: 2024.3.0
- Mushroom: 3.5.2
```
