### ISSUE TITLE
[Bug]: Secondary information not rendered in Template Card

### ISSUE THREAD

**Issue by lavinir** [piitaya/lovelace-mushroom#1410]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I'm trying to get the template card to show a list of the open windows. I wrote a template and tested it in the Dev Tools which is showing the proper output. However when inserting the template into the card I get empty output and nothing is rendered.

### Expected Behavior

The template output should be rendered in the card

### Steps To Reproduce

1. Create template card
2. Paste in YAML in the context below (assumes you have at least one binary sensor of class 'window' which is open

### Context

```yaml
type: conditional
conditions:
  - condition: state
    entity: binary_sensor.all_windows
    state: 'on'
card:
  type: custom:mushroom-template-card
  primary: There are open windows
  secondary: >-
    {% for state in states.binary_sensor if state.attributes.device_class ==
    'window' and state.state == 'on' %} {{ state.name }} {% endfor %}
  icon: mdi:window-open
  icon_color: '#FF9900'
  multiline_secondary: true


### Environment

```markdown
- Browser: Brave
- HA Version: 2024.4.3
- Mushroom:3.5.4
```
