### ISSUE TITLE
[Bug]: Entity chip card always show icon, even with icon_type: none

### ISSUE THREAD

**Issue by Spirituss** [piitaya/lovelace-mushroom#1416]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I'd like not to show icon for entity chip card. I use tag ```icon_type: none``` for the card but Lovelace still shows item icon.

### Expected Behavior

Chip card with no icon

### Context

YAML state
```
                        type: custom:mushroom-chips-card
                        chips:
                          - type: entity
                            entity: sensor.temperature
                            icon_type: none
```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.4.4
- Mushroom: 3.5.4
```
