### ISSUE TITLE
[Bug]: <Template Card tap-action: more-info>

### ISSUE THREAD

**Issue by 1iverea9er** [piitaya/lovelace-mushroom#1418]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I'm trying to set up `tap_action` for `more-info` in Template Card. But it not work with error:
"no object is specified for the dialogue box with additional information"

### Expected Behavior

I expect a window to be displayed with more information about the entity

### Context

YAML state
```yaml
                - type: custom:mushroom-template-card
                  entity_id: sensor.ac_lr_mode_shedule
                  primary: "{{states('sensor.ac_lr_mode_shedule') }}"
                  secondary: "AC LR Mode Shedule"
                  multiline_secondary: true
                  tap_action:
                        action: more-info
```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2025.5.1
- Mushroom: 3.5.4
```

### Anything else?

I traying other YAML state
```yaml
                - type: custom:mushroom-template-card
                  primary: "{{states('sensor.ac_lr_mode_shedule') }}"
                  secondary: "AC LR Mode Shedule"
                  multiline_secondary: true
                  tap_action:
                        action: more-info
                        entity: sensor.ac_lr_mode_shedule
```

**Comment by callumgare** [comment]
Try:
```
                - type: custom:mushroom-template-card
                  entity: sensor.ac_lr_mode_shedule # Note entity instead of entity_id
                  primary: "{{states('sensor.ac_lr_mode_shedule') }}"
                  secondary: "AC LR Mode Shedule"
                  multiline_secondary: true
                  tap_action:
                        action: more-info
```

Hopefully that gets it working for you. It's still quite confusing tho and I think the visual editor for the template card should give you an `entity` field so you can use the visual editor to work out the correct template.
