### ISSUE TITLE
[Feature]: More responsive `custom:mushroom-entity-card`

### ISSUE THREAD

**Issue by bilogic** [piitaya/lovelace-mushroom#1424]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

After tapping on the card once for some of my entities, the UI takes a while to react that I think something is wrong (a while = over 1 second)

The reason this happens is because I scripted some switches over MQTT, e.g. turning off wifi, blocking ads etc, and these do require the scripts to complete running. 

For HA's native on/off switch, what I observe is they change state immediately upon being clicked and only to revert back to original state if the script fails, this in my view is a better behavior

### Describe the solution you'd like

Follow HA's native switch implementation and toggle the UI immediately, and if the action fails, the entity state changes back again shortly

### Describe alternatives you've considered

n/a

**Comment by piitaya** [comment]
Do you have something set to `hold_action`? Try to set it to none and see if it's better.

**Comment by bilogic** [comment]
I don't think so, this is all
```
      - type: custom:mushroom-entity-card
        name: Ads
        entity: switch.router_ads
        tap_action:
          action: toggle
```
