### ISSUE TITLE
FR: add secondary option to cover, fan cards (or all?)

### ISSUE THREAD

**Issue by golles** [piitaya/lovelace-mushroom#144]
**Is your feature request related to a problem? Please describe.**
I'm currently replacing my current UI with mushroom components because I really like what you've been making and sharing, thanks for that!
At this moment, most of my UI is made with custom button cards, because there is an option to add labels.
I've got a cover entity (awning) that doesn't report a state, I've added a door/window sensor inside the awning to know if it's open or closed.
I've also got a fan entity (air purifier) where I not only show the state, but also the air quality.
<img width="303" alt="Schermafbeelding 2022-02-19 om 14 35 01" src="https://user-images.githubusercontent.com/2211503/154803200-48e4aefe-1661-43bf-880b-f7da0a12f80b.png">
(Zonnescherm = Awning, Gesloten = closed, coming from the door/window sensor)
(uit = off, Kwaliteit: Goed = Quality: Good)

**Describe the solution you'd like**
After playing with your template cards, I started to realize that the `secondary` option there is actually what I would love to see in more of the cards. That would allow me to use a template to get what I would like.
In my case, fan and cover would be great, but I can assume it's also interesting in other cards.

**Describe alternatives you've considered**
I've not considered any alternatives yet, only by omitting the state for the awning and the air quality of the air purifier:
<img width="453" alt="Schermafbeelding 2022-02-19 om 14 42 29" src="https://user-images.githubusercontent.com/2211503/154803329-427001ed-85ab-4605-9533-6e0a6611ce09.png">

**Additional context**
None for now, but thank you so much for making and sharing this!

**Comment by KTibow** [comment]
> I've got a cover entity (awning) that doesn't report a state, I've added a door/window sensor inside the awning to know if it's open or closed.

This could be fixed by using a template cover, Google it.

> I've not considered any alternatives yet, only by omitting the state for the awning and the air quality of the air purifier:

A hacky workaround is using `::after` with card-mod, eg:
```yaml
type: custom:mushroom-light-card
name: Bedroom
entity: light.bedroom_lights
icon: mdi:light-recessed
hold_action:
  action: navigate
  navigation_path: /lovelace-rooms/upstairs
fill_container: true
layout: vertical
style:
  mushroom-state-info$: |
    .secondary::after {
      content: " - {{ states("sensor.upstairs_temperature") }} °F";
    }
```
However I do agree having a custom secondary option in all cards would be useful.
