### ISSUE TITLE
[Feature]: Allow custom secondary_info

### ISSUE THREAD

**Issue by ceinmart** [piitaya/lovelace-mushroom#1447]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Trying to custom my mushroom-entity card , to show the time left on the timer of my switch. 

### Describe the solution you'd like

Something like:

```
type: custom:mushroom-entity-card
entity: switch.toalheiro
name: Toalheiro
tap_action:
  action: none
double_tap_action:
  action: call-service
  service: script.toalheiro_2h
  target: {}
icon_color: red
fill_container: false
primary_info: name
secondary_info: {{states("number.toalheiro_timer")}}
```

### Describe alternatives you've considered

found nothing until now...

### Additional context

Better dashboard customization and optimization where I can put the necessary info grouped.
