### ISSUE TITLE
[Bug]: button sometime disappearing after 2024.7 update

### ISSUE THREAD

**Issue by Shiroe93** [piitaya/lovelace-mushroom#1462]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

![immagine](https://github.com/piitaya/lovelace-mushroom/assets/56954468/7f23d186-7348-4c01-8278-9caada0f79ee)

### Expected Behavior

![immagine](https://github.com/piitaya/lovelace-mushroom/assets/56954468/a90ba051-b742-410c-8b61-933cd78330be)

### Steps To Reproduce

no idea it happens randomly and it's fixed by a refresh

### Context

YAML state
```
type: custom:vertical-stack-in-card
cards:
  - type: custom:mushroom-template-card
    primary: Shiroe-PC
    icon: mdi:desktop-tower
    entity: switch.shiroe_pc
    fill_container: true
    layout: vertical
    tap_action:
      action: call-service
      service: switch.turn_on
      target:
        entity_id: switch.shiroe_pc
    icon_color: '{{ ''brown'' if states(entity) == ''on'' else ''disabled''}}'
    double_tap_action:
      action: none
    secondary: ''
    badge_icon: ''
    picture: ''
    hold_action:
      action: navigate
      navigation_path: '#pcremote'
    card_mod:
      style: |
        ha-card {
          --icon-size: 45px;
            }
  - type: custom:mushroom-chips-card
    chips:
      - type: template
        entity: switch.switchbot_pc
        content_info: none
        icon_color: '{{ ''yellow'' if states(''switch.shiroe_pc'') == ''off'' else ''disabled''}}'
        icon: mdi:shield-link-variant
        tap_action:
          action: toggle
    alignment: center
```

### Environment

```markdown
- Browser: home assistant app 
- HA Version: 2024.7.1
- Mushroom: 3.6.2
```
