### ISSUE TITLE
[Bug]: Chip cards no longer staying at bottom of dashboard after 2024.7

### ISSUE THREAD

**Issue by dnestico** [piitaya/lovelace-mushroom#1464]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I have a chip card that acts as a back button on all my pages but after the update its no longer sticking, overlayed on top of everything at the bottom of the page anymore.

### Expected Behavior

Before the update, idk if its the mushroom update or HA 2024.7 it would overlay all the other cards just fine with card_mod.

### Context

YAML state
```yaml

  - type: custom:mushroom-chips-card
    chips:
      - type: action
        tap_action:
          action: navigate
          navigation_path: /lovelace/home
        hold_action:
          action: none
        double_tap_action:
          action: none
        icon: mdi:chevron-left
        card_mod:
          style: |
            ha-card {
              --chip-icon-size: 30px;
              background-color: var(--primary-color) !important;
            }
            ha-card:active {
              transform: scale(0.975);
              transition: 0s;
            }
    card_mod:
      style: |
        :host {
          z-index: 999;
          position: sticky !important;
          position: -webkit-sticky !important;
          bottom: 0;
          
        }
        ha-card {    
          padding-bottom: 15px;
          padding-left: 10px;
          # margin: 50px -10px -5px -10px;
          border-radius: 32px;
        }   


```

### Environment

```markdown
- Browser: Arc (chromium)
- HA Version: 2024.7.1
- Mushroom: 3.6.3
```
