### ISSUE TITLE
[Bug]: mushroom-light-card with no icon have weird paddings left and right to the slider

### ISSUE THREAD

**Issue by Krusenbaum** [piitaya/lovelace-mushroom#1479]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

A mushroom-light-card without any icon used to have a slider that lets me adjust the brightness of a lamp that filled the entire width of the container. After the 4.0 update, the slider has a padding left (where an icon would be if it had any) and right.

### Expected Behavior

No paddings left and right of slider
<img width="217" alt="Screenshot 2024-07-31 at 22 28 12" src="https://github.com/user-attachments/assets/24e843fe-2d22-4604-8455-b2be2cb22eb6">

### Steps To Reproduce

Create a mushroom-light-card without any icon:

- type: custom:mushroom-light-card
        entity: light.living_room_spots
        show_brightness_control: true
        show_color_control: false
        use_light_color: true
        layout: horizontal
        name: Spots
        **secondary_info: none
        primary_info: none
        icon_type: none**

### Context

YAML state
```yaml
- type: custom:mushroom-light-card
        entity: light.living_room_spots
        show_brightness_control: true
        show_color_control: false
        use_light_color: true
        layout: horizontal
        name: Spots
        secondary_info: none
        primary_info: none
        icon_type: none
```

### Environment

```markdown
- Browser: all
- HA Version: latest
- Mushroom: 4.0
```
