### ISSUE TITLE
[Bug]: Sizing with home assistant cast

### ISSUE THREAD

**Issue by jm-cook** [piitaya/lovelace-mushroom#1482]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Hi, I am using v4.0.0 with HA 2024.7.4

Recent changes to mushroom (and maybe HA?) have made the sizing of my cards slightly out when casting.  On a regular browser all is well, but when casting, the icon at the top spills into the border and the text at the bottom spills out below.
I am using sections (which is working better with mushroom now than a few weeks ago),
I am not using card-mod but I am using a custom mushroom theme.

Any hints how I can get the casted layout to match the browser layout?

Cast display:

![20240802_084920](https://github.com/user-attachments/assets/bec45a41-7446-4600-b239-a47f720d62ed)

It might just need a bit more padding, but how? Without using card-mod?

### Expected Behavior

Screenshot from browser:

![image](https://github.com/user-attachments/assets/c44d98ec-73a4-4002-81da-19c3f36dc8eb)

There is a tad more space above and below the content in each of the mushroom cards.

### Steps To Reproduce

```
    ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
    ha-card-border-radius: 16px !important
    ha-view-sections-column-gap: 8px
    ha-view-sections-row-gap: var(--ha-view-sections-column-gap)
    masonry-view-card-margin: 4px 4px 4px 4px
    # Mushroom layout
    # Default values are in comments. Uncomment to change.
    mush-spacing: 12px
    # Card
    mush-card-primary-font-size: 22px
    mush-card-secondary-font-size: 48px
    mush-card-primary-font-weight: 500
    mush-card-secondary-font-weight: 550
    mush-card-primary-line-height: 22px
    mush-card-secondary-line-height: 48px
    mush-card-primary-color: grey
    mush-card-border-radius: 18px
```

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: cast to Google nest hub
- HA Version: 2024.7.4
- Mushroom: 4.0.0
```

**Comment by jm-cook** [comment]
This is what I am getting now in a regular browser with 2024.8.0b1, and mushroom v 4.0.1, the problem looks similar to what I am seeing in the casted view. The change in mushroom card height is affecting the  vertical layout mode and there is not enough space around the edges.

![image](https://github.com/user-attachments/assets/6b6dce32-803e-4f1f-9612-eae2b9562c09)

View config:

```
  - title: test height
    path: test-height
    type: sections
    max_columns: 1
    theme: mush_nest_panel
    sections:
      - type: grid
        cards:
          - type: custom:mushroom-entity-card
            entity: sensor.indoor_temperature
            fill_container: true
            layout: vertical
```

Theme:

```
mush_nest_panel:
    # HA variables  
    ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
    ha-card-border-radius: 16px !important
    ha-view-sections-column-gap: 8px
    ha-view-sections-row-gap: var(--ha-view-sections-column-gap)
    masonry-view-card-margin: 4px
    # Mushroom layout
    # Default values are in comments. Uncomment to change.
    mush-spacing: 8px
    # Card
    mush-card-primary-font-size: 22px
    mush-card-secondary-font-size: 50px
    mush-card-primary-font-weight: 500
    mush-card-secondary-font-weight: 550
    mush-card-primary-line-height: 25px
    mush-card-secondary-line-height: 52px
    mush-card-primary-color: grey
    mush-card-border-radius: 18px
    # Chip
    mush-chip-border-radius: 25px
    mush-chip-font-size: 18px
    mush-chip-font-weight: bold
    mush-chip-icon-size: 0.5em
    mush-rgb-grey: 158, 158, 158
    mush-rgb-black: 0, 0, 0
    mush-rgb-white: 255, 255, 255



    # # You must keep this to support light/dark theme
    modes:
        light:
            mush-rgb-disabled: 189, 189, 189
        dark:
            mush-rgb-disabled: 111, 111, 111
```
