### ISSUE TITLE
[Bug]: Template card padding broken with HA 2024.08

### ISSUE THREAD

**Issue by MaJerle** [piitaya/lovelace-mushroom#1492]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Expected Behavior

WIth HA 2024.08, new heights are introduced in the dashboard.

### Steps To Reproduce

- Make sure you have HA 2024.08
- Add a new custom template to the sections.

### Context

YAML state
```yaml
type: custom:mushroom-template-card
primary: Refrigerator
secondary: >-
  {{ states('sensor.temp_hum_sensor_8_refrigerator_temperature') }} °C, {{
  states('sensor.athom_smart_plug_v2_u03_dd4f02_refrigerator_power') }} W,
  Doors: {{ states('sensor.refrigerator_number_of_opened_doors') }}
icon: mdi:home
layout_options:
  grid_columns: 4
  grid_rows: 1

```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.08
- Mushroom: v4.0.2
```

### Anything else?

Image:

![image](https://github.com/user-attachments/assets/3d1d72ee-054d-43b1-9c39-f053f2065314)
