### ISSUE TITLE
[Bug]: Custom element not found: mushroom-template-badge

### ISSUE THREAD

**Issue by pandamouse84** [piitaya/lovelace-mushroom#1495]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

In the iOS mobile app of home assistant I get the following error for all custom badges:
„Custom element not found: mushroom-template-badge„

In the web interface it works as expected.
Also the new HA 2024.8.x entity badges work without error.

### Expected Behavior

Custom badges are displayed and can be edited in the mobile app like in the web interface.

### Steps To Reproduce

1. Create a custom badge in a browser
2. Try to view the badge in the iOS app.

### Context

YAML state
```yaml

type: custom:mushroom-template-badge
tap_action:
  action: navigate
  navigation_path: /dashboard-statistik/pegelstand
hold_action:
  action: none
double_tap_action:
  action: none
icon: mdi:water
content: Pegelstand
visibility:
  - condition: or
    conditions:
      - condition: state
        entity: binary_sensor.ground_water_warning_exists
        state: 'on'
      - condition: state
        entity: binary_sensor.river_warning_exists
        state: 'on'
```

### Environment

```markdown
- Browser: iOS Companion App
- HA Version: 2024.8.1
- Mushroom: 4.0.2
```

### Anything else?
Screenshot:
![IMG_0468](https://github.com/user-attachments/assets/06508e48-23fc-428f-b174-8c4c608cab4b)
Companion App Bug: https://github.com/home-assistant/iOS/issues/2914
