### ISSUE TITLE
Add support for current_cover_tilt_position

### ISSUE THREAD

**Issue by martindybal** [piitaya/lovelace-mushroom#150]
**Is your feature request related to a problem? Please describe.**
I really like the component, but it doesn't allow me to adjust the tilt. 

**Describe the solution you'd like**
Add a tilt setting option if the entity supports `SUPPORT_SET_TILT_POSITION`. Functioning and design could be similar to `show_position_control`. When the button is clicked, the tilt setting slider is shown. 

**Describe alternatives you've considered**
There could be a whole new UI, but it's probably too much complicated and big
![image](https://user-images.githubusercontent.com/7644099/154895734-ebbc835a-8955-436a-b192-4670fcc88337.png)
![image](https://user-images.githubusercontent.com/7644099/154895766-fe75d8d1-dccc-48ae-af9d-124ac448e319.png)
![image](https://user-images.githubusercontent.com/7644099/154895788-6b7ef4c6-33bf-4bd8-a530-10aaf5945e40.png)

**Comment by martindybal** [comment]
Currently I'm using this setup. But it's not such a nice UI as `mushroom` provides
```
- type: entities
  entities:
    - type: custom:mushroom-cover-card
      entity: cover.103_office_blind_door
      show_buttons_control: true
      show_position_control: true
    - type: custom:slider-entity-row
      entity: cover.103_office_blind_door
      name: Tilt
      attribute: tilt
```
![image](https://user-images.githubusercontent.com/7644099/154896764-f398830c-8909-46e6-983b-c8075008c31e.png)
