### ISSUE TITLE
[Bug]: Badge label wrong class

### ISSUE THREAD

**Issue by skrepkaq** [piitaya/lovelace-mushroom#1529]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Since version 4.0.6, the badge label is rendered with the wrong class. This seems to have been introduced by #1527, which changed class names only in the CSS, and not in the DOM.
![image](https://github.com/user-attachments/assets/5d1e94d3-80ad-44ba-8792-5c9cd2886100)

### Context

YAML state
```yaml
type: custom:mushroom-template-badge
content: Content
icon: mdi:mushroom
color: red
label: Label
```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.8.3
- Mushroom: 4.0.6
```
