### ISSUE TITLE
[Feature]: Vertical orientation for sliders

### ISSUE THREAD

**Issue by jm-cook** [piitaya/lovelace-mushroom#1531]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I have only been able to show cards with a slider in the horizontal orientation. I would really like to replace the current solution I am using which is the inactive (development) custom bar-card.

### Describe the solution you'd like

Ideally the cards with sliders should also be able to be oriented vertically
![Screenshot 2024-09-03 103746](https://github.com/user-attachments/assets/83b95d1f-57e3-4906-b88b-5b48cde52cf3)

I'd like ideally to show the value of a sensor giving a volume which is not in the list of cards at the moment. The sensor would be best represented with a bar like indicator in the vertical orientation.
It would probably work with the input_number card with some fiddling on my part to update the helper when the sensor changes, but it would be an additional improvement if there were a generic sensor/entity card that also shows a bar with the possibility to set max/min values.

### Describe alternatives you've considered

I am currently using bar-card but it doesnt work well in sections view. I am also using config-template-card to extract max value for this bar-card. I like the result, but feel that it will break soon (height is fixed!), and it could be simplified with a good mushroom replacement.

![image](https://github.com/user-attachments/assets/55ef2e9f-e2c2-4b06-9ac4-3a8af390af1d)

```
type: custom:config-template-card
variables:
  gw: states['sensor.well_max_volume'].state
entities:
  - sensor.water_volume
element:
  type: custom:bar-card
  positions:
    indicator: inside
    name: inside
    icon: inside
  entities:
    - entity: sensor.water_volume
  direction: up
  height: 220px
  stack: horizontal
  severity:
    - color: Red
      from: 0
      to: 289
    - color: Orange
      from: 289.1
      to: 579
    - color: Green
      from: 579.1
      to: 825
  max: 825
  target: ${ parseFloat( gw) }
  card_mod:
    style: |
      bar-card-targetbar {--bar-color: var(--warning-color) !important;}
```
