### ISSUE TITLE
[Bug]: Icon Color on state doesn't work

### ISSUE THREAD

**Issue by paunsurfer** [piitaya/lovelace-mushroom#1539]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I am attempting to have a chip change the icon color based on the state of an entity (in this case a person's home or away status), but for some reason can't get it to function. I've tried the following: 

But the icon does not change color based on state, Am I missing something?

### Expected Behavior

The icon should be green when person.jordan state = home

### Steps To Reproduce

see post

### Context

YAML state
```type: custom:mushroom-chips-card
chips:
  - type: spacer
  - type: entity
    entity: person.jordan
    content_info: name
    icon_color: |-
      {% if is_state('person.jordan', 'home') %}
        green
      {% else %}
        white
      {% endif %}

```

### Environment

```markdown
- Browser: Chrome
- HA Version: 2024.8.3
- Mushroom: 4.0.7
```

**Comment by paunsurfer** [comment]
Update:

Simply setting an icon color actually results in the desired behavior and the icon and color become state sensitive. (I still think the yaml i used should have worked though)

working: 

``type: custom:mushroom-chips-card
chips:
  - type: spacer
  - type: entity
    entity: person.jordan
    icon_color: green
    content_info: name``

**Comment by swa72** [comment]
Nope, I observe the same on 2024.9.2.

```
type: horizontal-stack
cards:
  - type: custom:mushroom-entity-card
    entity: person.garden
    name: Garten
    tap_action:
      action: navigate
      navigation_path: /lovelace/garten
    icon: mdi:flower
    primary_info: name
    secondary_info: none
    icon_color: green
```
