### ISSUE TITLE
[Feature]: Entities Card

### ISSUE THREAD

**Issue by agnoam** [piitaya/lovelace-mushroom#1558]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Hey, I'm trying to convert this lovelace card into a mushroom alternative card. <br/>
![image](https://github.com/user-attachments/assets/cb3c0fad-0f7b-45d5-a923-5ae349218594)

I have managed to create such card: <br />
![image](https://github.com/user-attachments/assets/11eca54d-3343-4a92-8b50-f7a38db2d92f)

But I can't find an easy way to create the switch at the top that toggles all the included lights (as signed in a red circle) 

### Describe the solution you'd like

A card of multiple entities, that will create the signed switch automatically.
Such as the one provided by the basic UI.

**Comment by BBE-FR** [comment]
You can replace the "my room" part by a new (since 2024.10) heading card.
- You add inside this card an entity being a group of your equipments below
- You add the behavior to toggle the group to this entity

example with a section:
```
type: grid
cards:
  - type: heading
    heading: My Room
    heading_style: title
    badges:
      - type: entity
        show_state: false
        show_icon: true
        entity: group.lumieres_escalier
        color: state
        tap_action:
          action: toggle
  - type: tile
    entity: light.0x84b4dbfffec93621
  - type: tile
    entity: light.0x385b44fffe20eb24
```
![2024-11-08_09-36-55](https://github.com/user-attachments/assets/81ec679f-71a0-43be-af29-e0d414cefaf5)
