### ISSUE TITLE
[Bug]: Climate card: tap-action hardcoded to toggle?

### ISSUE THREAD

**Issue by koying** [piitaya/lovelace-mushroom#1571]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

```yaml
      - type: custom:mushroom-climate-card
        entity: climate.atelier
        show_temperature_control: true
        tap-action: 
          action: more-info
```

Even though I set the tap action of the card to "more-info", "toggle" is executed

### Expected Behavior

"more-info" is shown

### Environment

```markdown
- Browser: Firefox
- HA Version:2024.10
- Mushroom: 4.0.8
```

### Anything else?

I don't pretend to understand the code, but is it by design?
https://github.com/piitaya/lovelace-mushroom/blob/main/src/cards/climate-card/climate-card.ts#L121

If so, might be interesting to update the doc (https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/climate.md)
