### ISSUE TITLE
[Bug]: Curtain/Motor/Shutter control disable wrong button

### ISSUE THREAD

**Issue by marcopaggioro** [piitaya/lovelace-mushroom#1581]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

When shutter is open the modal shows "close" and viceversa.
Other the the wrong display mode, I can not bring down shutter due to the disabled button and viceversa
![image](https://github.com/user-attachments/assets/b6dcf495-ddf0-4881-8cb3-3741346917f2)

### Expected Behavior

Like little weeks ago, when the shutter is open the modal show "open" and viceversa.

Maybe a wrong state of the "sensors" or a problem with the modal? maybe the sensors return 100 instead of 0 and viceversa?

### Context

YAML state
```yaml
current_position: 100
device_class: blind
icon: mdi:window-shutter
friendly_name: Tapparella studio
supported_features: 15
```

### Environment

```markdown
- Browser: Chrome 130.0.6723.117
- HA Version: 2024.11.1
- Mushroom: 4.1.0
```
