### ISSUE TITLE
[Feature]: Individual chip visibility settings for Mushroom Chips Card

### ISSUE THREAD

**Issue by twerff** [piitaya/lovelace-mushroom#1623]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I'm trying to conditionally show chips in the Mushroom Chips Cards, but it's only possible to set visibility to the entire card.

### Describe the solution you'd like

```
type: custom:mushroom-chips-card
chips:
  - type: template
    entity: person.person1
    visibility:
      - condition: state
        entity: sensor.sensor1
        state: state
  - type: template
    entity: person.person2
    visibility:
      - condition: state
        entity: sensor.sensor2
        state: state
```
