### ISSUE TITLE
[Bug]: 4.3.0 Mushroom card display issue on Raspberry Pi

### ISSUE THREAD

**Issue by spidermedic** [piitaya/lovelace-mushroom#1665]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.
- [x] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

With the 4.3.0 update Mushroom cards stopped working on my Raspberry Pi.

The Pi is in kiosk mode for my magic mirror running Buster using OpenBox and Chromium. Resetting the cache and restarting the Pi had no effect, nor did restarting Home Assistant.

After deleting and rolling back to 4.2.1 the cards worked as before. The problem returned after updating to 4.3.0 again.

### Context

YAML state of a card that doesn't display:

```
type: custom:mushroom-entity-card
entity: switch.porch_light
grid_options:
  columns: 12
  rows: 1
tap_action:
  action: toggle
icon_color: yellow
```

### Environment

```markdown
- Browser: Chromium
- HA Version: 14.2
- Mushroom: 4.3.0
```
