### ISSUE TITLE
[Feature]: Modify alarm states icons

### ISSUE THREAD

**Issue by Emeraude998** [piitaya/lovelace-mushroom#1671]
### Requirements

- [x] I have updated Mushroom to the latest available version
- [x] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Hi,
Would it be possible to modify/customize the icons for the states of the alarm panel?

They seem to currently be set to:
```
armed_home -> mdi:home
armed_away -> mdi:lock
armed_night -> mdi:moon-waning-crescent
armed_vacation -> mdi:airplane
armed_custom_bypass -> mdi:shield
disarmed -> mdi:shield-off
```

I would like to be able to use other icons for those states.

### Describe the solution you'd like

I would like to be able to select the states I want to be present on the card and edit their icon either directly in the UI or by editing the yaml.
Something like:
```
type: custom:mushroom-alarm-control-panel-card
entity: alarm_control_panel.alarm-entity
states:
  - armed_away
    icon: fapro:leave-house
  - armed_night
    icon: fapro:house-night
  - disarmed
    icon: mdi:lock-open
fill_container: true
name: Alarme
layout: vertical
secondary_info: state
```

### Describe alternatives you've considered

I have tried using the card-mod to edit the icon but the svg path is directly written rather than the mdi: path.
