### ISSUE TITLE
[Feature]: Make optional / remove crop to circle when using entity picture in mushroom template card.

### ISSUE THREAD

**Issue by Getslow6** [piitaya/lovelace-mushroom#1680]
### Requirements

- [x] I have updated Mushroom to the latest available version
- [x] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

I'm trying to make a custom addon status card, where I'd like to use the entity pictures. Unfortunately, the Mushroom template card currently does not give an option to remove the 'cropping to circle' of the entity picture:

![Image](https://github.com/user-attachments/assets/226f1721-3cf9-4e7c-9ee8-d599bd31658f)

```
type: grid
cards:
  - type: custom:mushroom-template-card
    entity: update.ssh_web_terminal_update
    picture: "{{ state_attr( entity, \"entity_picture\") }}"
    primary: "{{ state_attr( entity, \"title\") }}"
    secondary: "{{ state_attr( entity, \"installed_version\") }}"
    grid_options:
      columns: full
  - type: tile
    entity: update.ssh_web_terminal_update
    features_position: bottom
    vertical: false
    show_entity_picture: true
    state_content: installed_version
    grid_options:
      columns: full
```

### Describe the solution you'd like

Would it be possible to add an option to enable/disable cropping?
