### ISSUE TITLE
[Bug]: Can no longer see template editor with conditional chips as of 2025.5

### ISSUE THREAD

**Issue by mcanning** [piitaya/lovelace-mushroom#1703]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.
- [x] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

It seems there is not longer an option to edit the template as part of conditional chips. I had just upgraded to 2025.5 yesterday as I believe it was working the other day. See the screenshot which is missing the 'Card' tab.

![Image](https://github.com/user-attachments/assets/e18d876e-b768-4ee2-ace8-f81c485c46fa)

### Expected Behavior

Conditions and Card tabs

![Image](https://github.com/user-attachments/assets/6746de7f-bb41-4db4-a07b-a51c8089ef48)

### Steps To Reproduce

Create conditional  template chip on 2025.5 and attempt to modify the template using the UI

### Context

YAML state
```yaml
type: conditional
conditions:
  - condition: numeric_state
    entity: sensor.open_windows_count
    above: 0
chip:
  type: template
  content: '{{ states.sensor.open_windows_count.state }}'
  icon_color: |-
    {% if states("sensor.open_windows_count") > 0 %} primary {% elif
        states("sensor.open_windows_count") == "unavailable" %} black {% else %} grey
        {% endif %}
  icon: |-
    {% if states("sensor.open_windows_count") == "on" %} mdi:window-open {% elif
        states("sensor.open_windows_count") == "unavailable" %} mdi:alert-box-outline {% else %} mdi:window-closed
        {% endif %}
  entity: sensor.open_windows_count
  tap_action:
    action: more-info

```

### Environment

```markdown
- Browser: Google Chrome Version 134.0.6998.198 (Official Build) (64-bit)
- HA Version: 2025.5
- Mushroom: 4.4.0
```

### Anything else?

Please close if this is a dupe
