### ISSUE TITLE
[Bug]: mushroom-alarm-control-panel-card not working on 2025.05

### ISSUE THREAD

**Issue by pierrehenrymuller** [piitaya/lovelace-mushroom#1707]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.
- [x] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

After upgrade to 2025.05 and 2025.05.1 and upgrade Alarmo to v1.10.8, the mushroom alarm control panel card see the state of alarm but can't arm or disarm the alarm.

With alarmo card, arm is working so it seems there is a problem with mushroom alarm control panel.

The error message appear when I test to arm alarm is :
`L'entité alarm_control_panel.maison ne prend pas en charge l'action alarm_control_panel.alarm_arm_home.`
A translation will be : `The alarm_control_panel.home entity does not support the alarm_control_panel.alarm_arm_home action.`

### Expected Behavior

Like before, when I click on an arm mode and set the pin code, alarm will be armed in the desirated mode.

### Steps To Reproduce

1. HAOS 15.2, HA 2025.5.1, Alarmo v1.10.8, Mushroom v4.4.0
2. config
```
type: custom:mushroom-alarm-control-panel-card
entity: alarm_control_panel.maison
states:
  - armed_night
  - armed_vacation
  - armed_away
  - armed_home
name: Alarme
grid_options:
  columns: full
  rows: 2
```
3. Run
- click on an arm mode other than disarmed
- set the pin code and validate
- error appear and arm mode not set
4. Error`L'entité alarm_control_panel.maison ne prend pas en charge l'action alarm_control_panel.alarm_arm_home.`

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```
