### ISSUE TITLE
[Bug]: Deprecation warning: mushroom-light-card still uses color_temp instead of color_temp_kelvin

### ISSUE THREAD

**Issue by alan-altruy** [piitaya/lovelace-mushroom#1720]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.
- [x] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

Hello,
Since a recent update of Home Assistant, using the `color_temp` argument in the `light.turn_on` service is deprecated in favor of `color_temp_kelvin`. The deprecation is planned to become a breaking change in Home Assistant 2026.1.

Currently, when using the **temperature slider in the `mushroom-light-card`**, it still sends the `color_temp` argument, which triggers a warning in the Home Assistant logs:

```
Got `color_temp` argument in `turn_on` service, which is deprecated and will break in Home Assistant 2026.1, please use `color_temp_kelvin` argument
```

This suggests the card is using `light.turn_on` with `data: color_temp`, which will need to be updated to `data: color_temp_kelvin`.

### Expected Behavior

The `mushroom-light-card` should be updated to use `color_temp_kelvin` instead of `color_temp` when sending the `light.turn_on` service call via the color temperature slider.

### Steps To Reproduce

1. Create a `mushroom-light-card` with a configuration like this:

   ```yaml
   type: custom:mushroom-light-card
   entity: light.my_light
   show_color_temp_control: true
   use_light_color: true
   ```

2. Move the color temperature slider of the card to change the color temperature.

3. See logs:

   ```
   Logger: homeassistant.components.light
   Source: components/light/__init__.py:321
   Integration: Light (documentation, issues)

   Got `color_temp` argument in `turn_on` service, which is deprecated and will break in Home Assistant 2026.1, please use `color_temp_kelvin` argument
   ```

### Context

**light.my_light:**
  ```yaml
min_color_temp_kelvin: 2202
max_color_temp_kelvin: 4000
min_mireds: 250
max_mireds: 454
supported_color_modes:
  - color_temp
  - rgb
friendly_name: Lumière Cuisine
supported_features: 0
color_mode: rgb
brightness: 122
color_temp_kelvin: null
color_temp: null
hs_color:
  - 27.945
  - 57.255
rgb_color:
  - 255
  - 177
  - 109
xy_color:
  - 0.497
  - 0.384
   ```

### Environment

```markdown
- Browser: Chrome / Android
- HA Version: 2025.5.0
- Mushroom: v4.4.0
```

### Anything else?

Thanks in advance for your work!
