### ISSUE TITLE
[Bug]: Title Card Small Title Font Size as of 2025.5.3

### ISSUE THREAD

**Issue by mcanning** [piitaya/lovelace-mushroom#1724]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.
- [x] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

The font size for the title card has been reduced as of the latest HA release. It is now a smaller font size than the sub-title. This is seen in chrome as well as the mobile app.

![Image](https://github.com/user-attachments/assets/77d33887-a5ea-44f2-a50e-bb5252f0338f)

### Expected Behavior

Expected size per the documentation

![Image](https://github.com/user-attachments/assets/a54ba623-bfc1-4871-9804-2792ad2aaa7f)

### Steps To Reproduce

Create a new title card with a title and save.

### Context

YAML state
```yaml
type: custom:mushroom-title-card
title: Upstairs
subtitle: >-
  {{states("sensor.average_bedroom_temp")|round(0)}}° |
  {{states("sensor.lumi_lumi_weather_humidity_3")|round(0)}}%
title_tap_action:
  action: navigate
  navigation_path: /matt-dash/upstairs
subtitle_tap_action:
  action: none
alignment: start
card_mod:
  style: |
    ha-card {
      --title-font-size: 400px !important;
      --subtitle-font-size: 10px !important;
    }

```

### Environment

```markdown
- Browser: Chrome Version 136.0.7103.142 (Official Build) (64-bit)
- HA Version: 2025.5.3
- Mushroom: v4.4.0
```
