### ISSUE TITLE
Transition property for light card

### ISSUE THREAD

**Issue by conorhub** [piitaya/lovelace-mushroom#234]
I don't believe there's currently a way to use a light bulb with a light card and have the light use its transition feature (fading in or out softly) unless the bridge implements it.

This is the case for something like the Philips Hue Bridge, using Hue light bulbs.

If you're to use the same Hue light bulb with something like a zigbee bridge, the transition is typically not automatically implemented and needs to be directly stated as a property by the action i.e. the mushroom card.

I can think of hacky ways of getting this to work involving scripts etc but thought it would defeat the purprose of mushroom being about simplicity. Might it be possible to include a transition property  for lights alongside the current settings? Thanks

**Comment by SaSa1983** [comment]
There's no need for this property.
You can use the tap action in conjuction with call-service (light.toggle) and the service allows to set the transition duration:

```
type: custom:mushroom-light-card
entity: light.my_light_entity
use_light_color: true
show_brightness_control: true
show_color_temp_control: true
show_color_control: true
tap_action:
  action: call-service
  service: light.toggle
  service_data:
    transition: 5
  target:
    entity_id: light.my_light_entity
```
