### ISSUE TITLE
Sorting entity card

### ISSUE THREAD

**Issue by Smiggel** [piitaya/lovelace-mushroom#290]
Feature request:
I would like to have an entity card that can sort the items you put on a card by entity attributes.

**Describe the solution you'd like**
 Something like: https://github.com/thomasloven/lovelace-auto-entities.

**Describe alternatives you've considered**
 I worked with https://github.com/thomasloven/lovelace-auto-entities. However, this card adds an extra border/background and the mushrooms entities card in this card, doesn't match the looks of the mushroom cards. So would like to see a "native" card that would match better with the mushroom theme and cards.

**Comment by ulic75** [comment]
I wonder if maybe your theme is doing that.  I've used auto-entites and I don't see additional styling going.

**Comment by j-loewen** [comment]
You have an extra border if you put mushroom cards in an entity card. This is what the above-mentioned card does. BUt there is a workaround you could do something like this:

```
type: custom:auto-entities
card:
  type: grid
  columns: 1
  square: false
card_param: cards
filter:
  include:
    - domain: light
      state: 'on'
      options:
        type: custom:mushroom-light-card
        use_light_color: true
        show_brightness_control: true
        show_color_temp_control: true
        show_color_control: true
  exclude: []
sort:
  method: last_changed
show_empty: false
```
