### ISSUE TITLE
Person Card - Icon displaying at top when no name and no state

### ISSUE THREAD

**Issue by capandcamera** [piitaya/lovelace-mushroom#314]
**Describe the bug**
When creating a vertical person card with no state and no name, the icon is positioned at the top of the card rather than in the centre.

**To Reproduce**
```
type: custom:mushroom-person-card
entity: person.[[ENTITY]]
use_entity_picture: true
hide_name: true
hide_state: true
layout: vertical
tap_action:
  action: none
hold_action:
  action: none
double_tap_action:
  action: none

```

**Screenshots**
<img width="170" alt="Screenshot 2022-04-15 at 09 21 13" src="https://user-images.githubusercontent.com/79606905/163546084-a2208c82-1b50-423a-97f2-98442b5a4356.png">

**Expected behavior**
<img width="170" alt="Screenshot 2022-04-15-expected" src="https://user-images.githubusercontent.com/79606905/163546264-4e0c535f-2e24-4b74-b027-23a48a738ec7.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome, Safari
