### ISSUE TITLE
Allow colored icon/slider corresponding to light color

### ISSUE THREAD

**Issue by pedolsky** [piitaya/lovelace-mushroom#35]
I'm deeply in love with your awesome project! 
Would it be possible to reflect the chosen light color in the icon and/or slider?

**Comment by ImagineerNL** [comment]
+1

This assumes you can select a light color in this card? i was unable to do so. am i missing something or is this not possible?
(i can select the color in another card, but not throught the light card)

**Comment by pedolsky** [comment]
Here is my code:

```
type: custom:mushroom-light-card
entity: light.hue_iris
vertical: true
show_brightness_control: true
show_color_temp_control: true
tap_action:
  action: toggle
hold_action:
  action: more-info

```
Have you defined the hold action?
