### ISSUE TITLE
Add a confirmation to locks as a 2nd step

### ISSUE THREAD

**Issue by steffenrapp** [piitaya/lovelace-mushroom#357]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It can happen that you accidentally tap on unlock or open at a lock. To prevent this it would be great to have an optional confirmation step after tapping on unlock or open at a lock.

**Comment by lukyjay** [comment]
I don't have a lock so not sure if it works the same, but Home Assistant offers this built in. This is how I did it on my template card:

```
type: custom:mushroom-template-card
primary: Garage door
secondary: >-
  {% if is_state('binary_sensor.door_entrance_1_contact', 'off') %}Closed{% else
  %}Open{% endif %}
icon: mdi:garage
entity: binary_sensor.door_garage_1_contact
tap_action:
  action: call-service
  service: switch.turn_on
  service_data: {}
  target:
    entity_id: switch.garage_door
  confirmation:
    text: Are you sure?
```

Have you tried adding those last two lines onto your card's code?
