### ISSUE TITLE
Smoke/CO/Heat Card

### ISSUE THREAD

**Issue by jaburges** [piitaya/lovelace-mushroom#366]
**Is your feature request related to a problem? Please describe.**
Nest Protects have multiple sensors:
Smoke
Heat
CO
Battery

**Describe the solution you'd like**
A simple (cool looking) card, like your others, with 3 simple circular sensor circles that goes red/does something if not OK or clear. 
And space for the Battery/connection state

**Describe alternatives you've considered**
custom button card, but can't make it look the same as the other cards.

**Additional context**

**Comment by jaburges** [comment]
this also could be used as printer ink status ?

**Comment by piitaya** [comment]
To keep mushroom simple, the rule is on entity = one card. As you you can see on the repo, there is a lot of feature requests. We prefer de focus on single entity for now.

**Comment by acesyde** [comment]
Hi @jaburges 

With [ertical stack in card](https://github.com/ofekashery/vertical-stack-in-card)

You can do something like that ;)

![image](https://user-images.githubusercontent.com/958435/164891289-2ef6d65e-b72f-49cd-be7f-e741dfec1784.png)

Code sample 

```yaml
type: custom:vertical-stack-in-card
title: Smoke Sensor
cards: 
  - type: custom:mushroom-cover-card
    name: Battery
    entity: cover.volets_roulant_jardin
    layout: horizontal
    show_buttons_control: true
  - type: custom:vertical-stack-in-card
    horizontal: true
    cards:
    - type: custom:mushroom-entity-card
      name: Humidity
      entity: sensor.0xa4c138a8b5d65736_humidity
    - type: custom:mushroom-entity-card
      name: Temperature
      entity: sensor.0xa4c138a8b5d65736_temperature
      layout: horizontal
```
