### ISSUE TITLE
[Bug]: media picture not always shown.

### ISSUE THREAD

**Issue by TheFes** [piitaya/lovelace-mushroom#429]
### Current Behavior

The media_picture is not always shown
![image](https://user-images.githubusercontent.com/28803438/166207523-28077e86-9236-4add-96d6-da0020e0341c.png)

I suspect it is related to me using a local picture when I start a radio stream using an automation or script.
Current attributes of the media_player shown in the picture:
```yaml
volume_level: 0.25
is_volume_muted: false
media_content_id: http://icecast.omroep.nl/radio2-bb-aac
media_content_type: music
media_position: 6531.736248
media_position_updated_at: '2022-05-02T08:34:35.133944+00:00'
media_title: Er is maar één NPO Radio 2
media_artist: NPO Radio 2
app_id: CC1AD845
app_name: Default Media Receiver
entity_picture_local: >-
  /api/media_player_proxy/media_player.zolder_mini_martijn?token=some_token
entity_picture: http://192.168.2.3:8123/local/pictures/radio/npo_radio_2.jpg
friendly_name: Zolder Mini Martijn
supported_features: 152463
```

It works on the more_info display:
![image](https://user-images.githubusercontent.com/28803438/166209498-32e05909-32ae-4d05-bf55-985c6ddd6463.png)

### Expected Behavior
I expect it to look like this (it works when I use a voice command to stream from TuneIn)
![image](https://user-images.githubusercontent.com/28803438/166207984-1294189e-2130-4cb1-9d30-21fe3f4bc358.png)

attributes:
```yaml
volume_level: 0.25
is_volume_muted: false
media_position_updated_at: '2022-05-02T08:42:47.497212+00:00'
app_id: 12F05308
app_name: TuneIn Free
entity_picture_local: >-
  /api/media_player_proxy/media_player.zolder_mini_martijn?token=another_token
friendly_name: Zolder Mini Martijn
supported_features: 152461
media_content_id: http://icecast.omroep.nl/radio2-bb-aac
media_position: 1.277273
media_content_type: music
media_title: The Pointer Sisters - Happiness
media_artist: NPO Radio 2
entity_picture: https://cdn-albums.tunein.com/gn/TLLBNR91NMg.jpg
```

### Steps To Reproduce

Start a stream using the following service call:
(of course change the picture url to something existing, is has to be a full url though, not an internal HA link and change the media_player to an existing player)

```yaml
alias: "Turn on Radio 2"
service: media_player.play_media
target:
  entity_id: media_player.some_media_player
data:
  media_content_id: "http://icecast.omroep.nl/radio2-bb-aac"
  media_content_type: music
  extra:
    metadata:
      metadataType: 3
      title: "Er is maar één NPO Radio 2"
      artist: "NPO Radio 2"
      images:
        - url: "http://your_ip:8123/local/pictures/a_picture.jpg"
```

### Environment

```markdown
- OS: HA OS 8.0 rc3
- Browser: Chrome
- Version: 
- Hassio: 2022.5.0b5
- Media Player: Google Nest Mini
```
