### ISSUE TITLE
[Feature]: Confirmation after tap

### ISSUE THREAD

**Issue by alnavasa** [piitaya/lovelace-mushroom#477]
### Is your feature request related to a problem?

NO

### Describe the solution you'd like

I was using multi entity card in the past that had a confirmation popup made so for critical buttons (door openers alarms....) had a pop up to confirm,

### Describe alternatives you've considered

The code was like this:

```
  - entity: switch.abridor_puerta
    name: false
    icon: mdi:remote
    tap_action:
      action: toggle
      confirmation:
        text: Are you sure?


```

### Additional context

card used previously: type: custom:multiple-entity-row

**Comment by alnavasa** [comment]
as easy as this:


```
type: custom:mushroom-entity-card
entity: switch.depuradora_piscina
layout: vertical
icon: mdi:fan
name: Depuradora
secondary_info: none
fill_container: true
tap_action:
  action: toggle
  confirmation:
    text: ¿Estas Seguro de que quieres encender depuradora?
```
