### ISSUE TITLE
[Feature]: Fully Customizable Vacuum Buttons

### ISSUE THREAD

**Issue by jaredguiles** [piitaya/lovelace-mushroom#483]
### Is your feature request related to a problem?

Would love to be able to customize the vacuum card further to adapt to other types of "vacuums" and vacuum functions. 

Since the "vacuum" entity is used for other types of devices as well as possibly having different functions/services than the standard ones included, it would be nice to be able to change the button icons, and service calls. For example, I have a Litter-Robot that is registered as a vacuum, however, the actions are different from a vacuum so the buttons don't work. 

![Screen Shot 2022-05-13 at 10 33 03](https://user-images.githubusercontent.com/43616413/168337370-32762d95-38c1-40dd-bee4-95232a996895.png) 
![Screen Shot 2022-05-13 at 10 33 10](https://user-images.githubusercontent.com/43616413/168337324-30b26168-1eb9-45d0-a90c-981e68f7d600.png)

### Describe the solution you'd like

Change the command checkbox options into standard service call options like the normal entity actions. Possibly pre-fill with standard start/stop, locate, return home, etc. but give the ability to change those service calls to be something else (not locked down by the vacuum entity). 

Example (vacuum.start & button.press calls):

![Screen Shot 2022-05-13 at 10 32 00](https://user-images.githubusercontent.com/43616413/168337189-1e564e0e-3c2d-4bf9-84bd-9711456b6237.png)

### Describe alternatives you've considered

I have built the example above using custom button-cards and chips (for the battery & waste bin) with heavy CSS work. Lots of code, and not very sustainable.

**Comment by posreg** [comment]
not the exaact resolution, but workaround, you can have buttons / states for every attribute or script 

mine example

![image](https://user-images.githubusercontent.com/80816020/168685946-61acd2aa-14ff-45da-ac1d-a42818876d85.png)

**Comment by piitaya** [comment]
May be adding custom buttons to entity card makes more sense that adding them to vacuum card?

**Comment by alessandroias** [comment]
> May be adding custom buttons to entity card makes more sense that adding them to vacuum card?

It could be useful for fan modes too.

**Comment by jaredguiles** [comment]
> May be adding custom buttons to entity card makes more sense that adding them to vacuum card?

Yes, I think that would be better. It would give more options for other entities as well like @alessandroias mentioned.

**Comment by KTibow** [comment]
Could we merge this issue into #341?

**Comment by briandonahue** [comment]
@jaredguiles side question - how do you have the battery percentage displayed on the card, I don't see a way?

**Comment by jaredguiles** [comment]
> @jaredguiles side question - how do you have the battery percentage displayed on the card, I don't see a way?

@briandonahue, technically it is not in the card, but on top of using a bit of CSS and using 'stack-in-card'. Not how I want to do it, but it works. 

``` yaml
type: vertical-stack
cards:
  - type: custom:mushroom-vacuum-card
    entity: vacuum.deebot_500
    commands:
      - start_pause
      - locate
      - return_home
    icon: fapro:svgs/solid/vacuum-robot
    name: Robot Vacuum
    tap_action:
      action: none
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: custom:stack-in-card
    mode: vertical
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: sensor.vacuum_battery
            icon: fapro:svgs/solid/battery-full
            style: |
              ha-card {
                box-shadow: none !important;
                background-color: transparent !important;
              }
              ha-card .content {
                padding: 3px !important;
              }
        alignment: end
    style: |
      ha-card {
        position: absolute;
        top: 4px;
        right: 20px;
        box-shadow: none;
        background-color: transparent;
      }
```
