### ISSUE TITLE
Feature Request Color Template

### ISSUE THREAD

**Issue by apfelflo89** [piitaya/lovelace-mushroom#49]
Hey, would it be possible to get the color not static? I'd love to see a color template so I could set the color in combination with an entities state. 
My use case would be the color of garbage bins I need to get in front of the house

**Comment by piitaya** [comment]
Hello 🙂
You can use template card to do this : https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/template.md

For example :
```yaml
type: custom:mushroom-template-card
primary: Number of entities
secondary: |
  {{ states | count }} entities
icon: mdi:format-list-bulleted
icon_color: |
  {{ "green" if states | count > 50 else "red" }} 
```
