### ISSUE TITLE
[Feature]: Add scene card

### ISSUE THREAD

**Issue by wgregorian** [piitaya/lovelace-mushroom#536]
### Is your feature request related to a problem?

Adding a scene card would be great; currently, the only way is to add a Chip card, which requires two steps, one to call the scene and two to activate.

### Describe the solution you'd like

A scene card that can activate with a single-click, I haven't figured out how to do achieve this with the existing chip card.

**Comment by pnichols77** [comment]
Use the scene.turn_on service as the action for a chip, and give it the scene entity you want to turn on.

```
service: scene.turn_on
data: {}
target:
  entity_id: scene.evening_lights

```

**Comment by piitaya** [comment]
You can also use the `custom:mushroom-entity-card`. Just use the `turn_on` service instead of toggle. Toggle is not supported by scene because a scene can't be turned off.

**Comment by acesyde** [comment]
Hi you can do something like that

```yaml
type: custom:vertical-stack-in-card
horizontal: true
cards:
      - type: custom:mushroom-entity-card
        entity: scene.salon_dodo
        name: Dodo
        layout: vertical
        hide_icon: false
        primary_info: name
        secondary_info: none
        icon: mdi:sleep
        icon_color: white
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data: {}
          target:
            entity_id: scene.mode_dodo
      - type: custom:mushroom-entity-card
        entity: scene.salon_tv
        name: TV
        layout: vertical
        hide_icon: false
        primary_info: name
        secondary_info: none
        icon: mdi:television
        icon_color: yellow
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data: {}
          target:
            entity_id: scene.scene_tv
      - type: custom:mushroom-entity-card
        entity: scene.salon_repas
        name: Repas
        layout: vertical
        hide_icon: false
        primary_info: name
        secondary_info: none
        icon: mdi:silverware-spoon
        icon_color: light-blue
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data: {}
          target:
            entity_id: scene.mode_miam
```
