### ISSUE TITLE
[Bug]: Conditionnal card keep its space

### ISSUE THREAD

**Issue by Aohzan** [piitaya/lovelace-mushroom#551]
### Current Behavior

When I add conditional cards, and the card is hidden, the dashboard keep the space allowed to the card instead of free it for the next card. It works with my "classic" dashboard with integrated cards: the next visible card shows up directly after the other, no empty space.

![image](https://user-images.githubusercontent.com/2736322/173331528-df983be6-5a4b-4bbd-a244-257450dbcbb5.png)

Edit mode:
![image](https://user-images.githubusercontent.com/2736322/173331606-e1b40548-4d0b-454a-8f76-e3cab93ccd1b.png)

### Expected Behavior

(when I remove conditional cards)
![image](https://user-images.githubusercontent.com/2736322/173331716-c56867ea-3e5b-4487-9318-6b79ccaa0c53.png)

### Steps To Reproduce

Add a conditional card, example:
```yaml
      - card:
          type: custom:mushroom-entity-card
          entity: select.harmony_hub_salon_activities
          name: Harmony Salon
        conditions:
          - entity: binary_sensor.presence_salon
            state: "on"
        type: conditional
```

### Environment

```markdown
- OS: Arch Linux
- Browser: Firefox
- Version: 101.0.1
- Hassio: 2022.6
```

### Anything else?

Thank you :)
