### ISSUE TITLE
[Feature]: Collapsible group card

### ISSUE THREAD

**Issue by KTibow** [piitaya/lovelace-mushroom#566]
### Is your feature request related to a problem?

Right now, if I want to have a toggle for a light group but also be able to control the individual lights, I have to either make separate cards or give up on controlling the different lights.

### Describe the solution you'd like

A light card that can expand into the different lights inside of the group.

### Describe alternatives you've considered

Add a separate card for each light, or use browser-mod to show a card in a popup on hold/double tap

### Additional context

[Poor quality] mockup:
![image](https://user-images.githubusercontent.com/10727862/174486134-008a9658-5edd-4654-b64c-cfb1be6fe36e.png)
![image](https://user-images.githubusercontent.com/10727862/174486268-5e5a2ef8-c6f7-42ba-bb0c-b1977edcea4d.png)
You would do this by looking at the `entity_id` attribute:
![image](https://user-images.githubusercontent.com/10727862/174486310-cd86f83b-4f71-4a51-b58c-893429c17176.png)

**Comment by TheHolyRoger** [comment]
Would love this!

**Comment by Haloooch** [comment]
Just want to add a +1 to this request. I'm currently doing it through conditional cards but that's a complex solution for what seems like a frequent use case.

**Comment by KTibow** [comment]
@piitaya could you transfer this issue into a discussion (if you feel it would help)?

**Comment by JSAnyone** [comment]
Since all my cards are build this way right now, this missing feature is what keeps me of away from switching to mushroom cards.
Maybe the [code from here](https://github.com/thomasloven/lovelace-fold-entity-row) can help you implementing it?

![7CF39675-B789-4537-9974-89211394C99B](https://user-images.githubusercontent.com/74502558/190927060-b92e5040-ed0d-4c6f-8405-c8a3708fb6cd.jpeg)

**Comment by jscmidt** [comment]
I've implemented it with help of the `custom:fold-entity-row`. However, it doesn't look very good, destroys the mushroom philosophy since you have to use YAML and the card isn't meant to be used like that...

It's a nice trick to use it right now, but doesn't solve the request that this should be implemented directly into mushroom.


```
type: custom:fold-entity-row
open: false
head:
  type: custom:mushroom-light-card
  layout: horizontal
  show_brightness_control: true
  use_light_color: true
  show_color_control: true
  entity: light.julian_ambiente
entities:
  - type: custom:mushroom-light-card
    layout: horizontal
    show_brightness_control: true
    use_light_color: true
    show_color_control: true
    entity: light.meross_bulb_2
  - type: custom:mushroom-light-card
    layout: horizontal
    show_brightness_control: true
    use_light_color: true
    show_color_control: true
    entity: light.meross_bulb_1
  - type: custom:mushroom-light-card
    layout: horizontal
    show_brightness_control: true
    use_light_color: true
    show_color_control: true
    entity: light.led_controller_1
  - type: custom:mushroom-light-card
    layout: horizontal
    show_brightness_control: true
    use_light_color: true
    show_color_control: true
    entity: light.led_controller_2
```


![image](https://user-images.githubusercontent.com/74502558/209792324-82ba8543-856a-4339-8308-882ed5f1fd7d.jpeg)
![image](https://user-images.githubusercontent.com/74502558/209792352-6e67d536-a259-4e07-8980-43a6203634b6.jpeg)
