### ISSUE TITLE
[Feature]: Controls on template card

### ISSUE THREAD

**Issue by Gnol86** [piitaya/lovelace-mushroom#587]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I think that add controls to template card is a good idea. Custom button, slider and more.
I tried to develop that myself but is too complicated for me.

![MS Paint _ Microsoft Paint Online](https://user-images.githubusercontent.com/24519929/176720024-e8649b20-d304-40a5-8957-7d3442241aaf.png)

```
type: custom:mushroom-template-card
primary: Outside temperature
secondary: '{{ states(''sensor.outside_temperature'') }}°C'
icon: mdi:sun-thermometer-outline
controls:
  - type: slider
    min: 0
    max: 35
    value: '{{ states(''sensor.outside_temperature'') }}'
    color: >-
      {{ iif(states('sensor.outside_temperature') | int < 18, 'blue',
      iif(states('sensor.outside_temperature') | int > 23, 'red', 'green')) }}
  - type: spacer
  - type: button
    icon: mdi:roller-shade
    tap_action:
      action: call-service
      service: cover.open_cover
      data: {}
      target:
        entity_id: cover.living_room_window
    hold_action:
      action: none
    double_tap_action:
      action: none
  - type: button
    icon: mdi:roller-shade-closed
    tap_action:
      action: call-service
      service: cover.close_cover
      data: {}
      target:
        entity_id: cover.living_room_window
    hold_action:
      action: none
    double_tap_action:
      action: none
```
If you want the slider to be editable. We can use the value of this one with the variable "value" in the template
```
- type: slider
  min: 0
  max: 100
  value: '{{ states(''sensor.outside_temperature'') }}'
  slide_action:
    action: call-service
    service: cover.set_cover_position
    data:
      position: {{value}}
    target:
      entity_id: cover.living_room_window
```
It's not perfect (like my English) but I think the idea is worth exploring.

### Additional context

As for the editor. I'm thinking something like the Chips editor.
Controls list:

> Slider
```
- type: slider
  min:
  max:
  value:
  color:
  slide_action:
```
> Button
```
- type: button
  icon:
  color:
  tap_action:
  hold_action:
  double_tap_action:
```
> Conditional
```
- type: conditional
  conditions:
  control:
```
> Spacer
```
- type: spacer
```
