### ISSUE TITLE
[Feature]: <title>

### ISSUE THREAD

**Issue by usernein** [piitaya/lovelace-mushroom#593]
### Is your feature request related to a problem?

In my dashboard i don't use double click events at all: it's only clicks and holds. When i can, i always change the hold time to ~300ms to make it feel faster, but mushroom afaik doesn't allow you to change the [holdTime](https://github.com/piitaya/lovelace-mushroom/blob/2c97cbf2692b637367a780cbbfe1b476c30bc3b8/src/ha/panels/lovelace/common/directives/action-handler-directive.ts#L37)

Also, in mobile, if i don't take the finger off the screen, the hold_action doesn't get called. This behavior also makes it feel slower

### Describe the solution you'd like

An option to customize holdTime and an option to tell that i want to trigger hold_action even if i don't take the finger off the screen. e.g.
```yaml
hold_action:
  action: more-info
  haptic: success
  holdTime: 300
  cancelThreshold: 1000 # cancel event only after this. If the option is undefined, trigger hold_action immediately after reached holdTime
```
