### ISSUE TITLE
[Feature]: Confirmation for door lock mushroom card 

### ISSUE THREAD

**Issue by oetken** [piitaya/lovelace-mushroom#610]
### Is your feature request related to a problem?

When using hassio from the smartphone I sometimes accidentally tap a button. For stuff like door locks I always use confirmation dialog to make sure this is not happening.

### Describe the solution you'd like

A new option to require a confirmation when unlocking/opening would be great to avoid accidental unlocking.

### Describe alternatives you've considered

I tried the following without success:
```
type: custom:mushroom-lock-card
entity: lock.<XXX>
tap_action:
  action: default  # or toggle
  confirmation:
    text: Are you sure you?
```
