### ISSUE TITLE
[Feature]: add preset mode to climate card

### ISSUE THREAD

**Issue by piitaya** [piitaya/lovelace-mushroom#615]
### Is your feature request related to a problem?

Preset support to climate card can be awesome 🚀

### Describe the solution you'd like

List of buttons like HVAC modes 

### Describe alternatives you've considered

Use more info dialog

### Additional context

It can difficult to support custom presets.

**Comment by ENDERCAFe** [comment]
I would like to ask if the climate card can adjust the fan speed for example low mid high auto

**Comment by Jan-Arild-Blekken** [comment]
Is it possible to choose a sensor entity in the secondary information field? I use a seperate temperatur sensor in each room to read out the temperature but the temperature controll is on another unit.

**Comment by piitaya** [comment]
Card will be adjusted with user feedbacks 🙂

**Comment by joaovitoriasilva** [comment]
Love the new climate card.
The only thing missing is the ability to control fan speed. Example bellow. Can this be added?
![image](https://user-images.githubusercontent.com/8648976/179504641-e998d5fa-0f38-4000-9ea5-908a307b4db9.png)

**Comment by KimHEF** [comment]
Anything new here?

**Comment by ritech** [comment]
need adjust fan speed

**Comment by GoNzCiD** [comment]
I'm also interested into this, at least to be able to show the preset mode will be very interesting, for instance in the secondary field, instead of the mode that can be shown in the icon

**Comment by GitHubGoody** [comment]
+1

**Comment by deel77** [comment]
as @Jan-Arild-Blekken it would be great if I can change status text from `Heat - 22°C` to just `22°C` so use only custom attribute value or template value, as showing long text is cutting temperature from my mobile dense view and operation of "Heat" is sufficiently showed by color of icon

**Comment by thomasddn** [comment]
My temperature (heating only) is controlled by an external system, integrated into HA using MQTT and command topics. Being able to hit preset buttons directly from the temperature card would be way more convenient.

**Comment by jeroenvdd** [comment]
> My temperature (heating only) is controlled by an external system, integrated into HA using MQTT and command topics. Being able to hit preset buttons directly from the temperature card would be way more convenient.

Same my heating uses presets to switch between schedule / manual override.
It would be great to bale able to set presets + show them as secondary info too

**Comment by znidaxp** [comment]
I would love a possibility to use presets with this card. I hope it is coming soon.

**Comment by pepsonEL** [comment]
+1

**Comment by tpasc** [comment]
+1 would love to be able to control fan speed through this card

**Comment by GreenSkol** [comment]
+1 for fan mode support.

Fun fact, the screenshots on the official documentation page for "Features for dashboard cards" shows Mushroom card with fan mode support:

https://www.home-assistant.io/dashboards/features#climate-fan-modes

**Comment by doenau** [comment]
> +1 for fan mode support.
> 
> Fun fact, the screenshots on the official documentation page for "Features for dashboard cards" shows Mushroom card with fan mode support:
> 
> https://www.home-assistant.io/dashboards/features#climate-fan-modes

I think you will find that they use the Tile card in the example (look at the screenshot at the top)

**Comment by Merkalov** [comment]
![image](https://github.com/user-attachments/assets/d6222466-111f-4d11-8d2b-4f9ffbd68009)

Alternatively...

type: tile
entity: climate.konditsioner_2
icon: mdi:fan
hide_state: true
name: Fan speed
features:
  - type: climate-fan-modes
    style: icons
    fan_modes:
      - 'off'
      - low
      - medium
      - high

**Comment by lordcoxis** [comment]
+1 would love a possibility to use presets with this card.

**Comment by giuvincenzi** [comment]
+1 Are there any updates? It would be nice to control the fan separately

**Comment by s0ftice** [comment]
My workaround for now
![image](https://github.com/user-attachments/assets/1a0c77de-5d67-4310-9325-4bdf6a2321f6)

Tile card with the spinbox and drop down in a single feature using https://github.com/Nerwyn/service-call-tile-feature

**Comment by AlexNikitos** [comment]
> My workaround for now ![image](https://github.com/user-attachments/assets/1a0c77de-5d67-4310-9325-4bdf6a2321f6)
> 
> Tile card with the spinbox and drop down in a single feature using https://github.com/Nerwyn/service-call-tile-feature

Yaml please :)

**Comment by s0ftice** [comment]
```
type: tile
entity: climate.aircon06
name: Air Conditioner
icon_tap_action:
  action: perform-action
  perform_action: switch.toggle
  target:
    entity_id: switch.aircon06_on_off
hide_state: false
features_position: bottom
vertical: false
state_content: state
features:
  - type: custom:service-call
    entries:
      - type: spinbox
        label: "{{ value }}{{ unit }}"
        step: 1
        debounceTime: 0
        range:
          - "{{ state_attr(\"climate.aircon06\", \"min_temp\") }}"
          - "{{ state_attr(\"climate.aircon06\", \"max_temp\") }}"
        value_attribute: temperature
        unit_of_measurement: °C
        hold_action:
          action: repeat
        entity_id: climate.aircon06
        styles: |-
          :host {
            --background: var(--feature-color);
            --icon-color: var(--feature-color);
            flex-flow: row;
            flex-basis: 180%;
          }
        tap_action:
          action: perform-action
          perform_action: climate.set_temperature
          target:
            entity_id: climate.aircon06
          data:
            temperature: "{{ value }}"
      - type: dropdown
        value_attribute: fan_mode
        entity_id: climate.aircon06
        options:
          - icon: mdi:fan-auto
            entity_id: climate.aircon06
            option: auto
            tap_action:
              action: perform-action
              perform_action: climate.set_fan_mode
              data:
                fan_mode: auto
              target:
                entity_id: climate.aircon02
            type: dropdown
          - icon: mdi:fan-speed-1
            entity_id: climate.aircon06
            option: low
            tap_action:
              action: perform-action
              perform_action: climate.set_fan_mode
              data:
                fan_mode: low
              target:
                entity_id: climate.aircon06
            type: button
          - icon: mdi:fan-speed-2
            entity_id: climate.aircon06
            option: medium
            tap_action:
              action: perform-action
              perform_action: climate.set_fan_mode
              data:
                fan_mode: medium
              target:
                entity_id: climate.aircon06
            type: button
          - icon: mdi:fan-speed-3
            entity_id: climate.aircon06
            option: middle
            tap_action:
              action: perform-action
              perform_action: climate.set_fan_mode
              data:
                fan_mode: middle
              target:
                entity_id: climate.aircon06
            type: button
          - icon: none
            entity_id: climate.aircon06
            option: high
            tap_action:
              action: perform-action
              perform_action: climate.set_fan_mode
              data:
                fan_mode: high
              target:
                entity_id: climate.aircon06
            type: button
            styles: |-
              ha-icon {
                background-color: currentColor;
                mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='m13,19c0,-1.41 0.5,-2.7 1.3,-3.72c-0.13,-0.31 -0.27,-0.63 -0.44,-0.94c0.4,-0.34 0.71,-0.75 0.91,-1.23c0.49,0.1 1.01,0.28 1.48,0.56c0.82,-0.42 1.75,-0.67 2.75,-0.67c1.05,0 2.03,0.27 2.89,0.74c0.06,-0.37 0.11,-0.78 0.11,-1.24c0,-3.58 -3.97,-4.37 -7.67,-2.37c-0.33,-0.4 -0.74,-0.71 -1.22,-0.91c0.19,-0.93 0.63,-1.98 1.62,-2.47c2.36,-1.18 2.27,-4.75 -2.23,-4.75c-3.57,0 -4.36,3.96 -2.37,7.65c-0.41,0.32 -0.73,0.74 -0.92,1.22c-0.93,-0.19 -1.98,-0.62 -2.48,-1.61c-1.17,-2.37 -4.73,-2.26 -4.73,2.24c0,3.57 3.95,4.35 7.64,2.37c0.32,0.4 0.75,0.72 1.24,0.92c-0.2,0.92 -0.64,1.96 -1.62,2.45c-2.36,1.18 -2.26,4.76 2.24,4.76c0.81,0 1.5,-0.22 2,-0.59c-0.31,-0.74 -0.5,-1.55 -0.5,-2.41m-1,-6c-0.57,0 -1,-0.45 -1,-1s0.43,-1 1,-1c0.54,0 1,0.45 1,1s-0.46,1 -1,1m4.92,1.96l-1.54,0l0,4.12l2.71,0l0,3.83l1.96,0l0,-8l-1.77,0l0,2.43l-1.28,0l0,-2.36z'/%3E%3C/svg%3E");
              }
    styles: |
      :host {
        --feature-button-spacing: 6px;
      }

```

Note, there is no mdi:fan-speed-4, that's why I SVG'ed it myself.

Have fun! :)
