### ISSUE TITLE
[Bug]: Missing climate temperature controls icon colors

### ISSUE THREAD

**Issue by ulic75** [piitaya/lovelace-mushroom#622]
### Current Behavior

My plus/minus icons just use the default browser button styling, which results in white icons which are pretty much not visible.
![Screen Shot 2022-07-18 at 9 30 57 AM](https://user-images.githubusercontent.com/5641964/179547376-68dcd57e-aa94-4f36-bd4c-8135de3a2b95.png)

### Expected Behavior

To be able to see them :)

### Environment

```markdown
- OS: HA OS
- Browser: Brave & Firefox
- Version: 2.1.1
- Hassio: 2022.7.5
```

### Anything else?

I'll submit a PR.  I fixed it by mirroring the icon/button setup from button.ts adding the following three things.

```css
:host {
    --icon-color: var(--primary-text-color);
    --icon-color-disabled: rgb(var(--rgb-disabled));
.button ha-icon {
    color: var(--icon-color);
}
```
