### ISSUE TITLE
[Feature]: Add repeated card based on wildcards

### ISSUE THREAD

**Issue by postlund** [piitaya/lovelace-mushroom#652]
### Is your feature request related to a problem?

My problem is that I add a lot of the same kind of card, e.g. lots of light cards, that require a lot of repetitive work.

### Describe the solution you'd like

I want to be able to pick one card type, e.g. light or template, enter some wild card criterias to filter out entities (e.g. `light.downstair_*`) and generate one card for each of the entities from the filter. I imagine the output would correspond to a table view, so number of columns should be configurable. Information about each entity must be available via a variable (so the selected card can be customizable based on each filtered entity).

### Describe alternatives you've considered

Manually add cards for each entity or copy paste yaml code. Both solutions are cumbersome and error prone.

### Additional context

An improvement would be to treat this card as a vertical stack, allowing multiple cards to be selected (with individual filters for each card) and allowing global sorting of all generated cards. This would make it possible to filter out things like all lights, switches and vacuums and display them "in order" without introducing potential empty spaces like would happen if multiple cards (of this type) are added.

**Comment by piitaya** [comment]
Hello🙂
You can use [auto-entities card](https://github.com/thomasloven/lovelace-auto-entities) combined with mushroom card do to this 🙂

**Comment by fanuch** [comment]
@piitaya is right on and I'll do you one better.

Go add auto-entities cards and paste this in, which will:
* Display all "light" entites; only
* Friendly name starts with `stairs_`

Bonus, it's a grid layout so you can adjust how many appear per row

![image](https://user-images.githubusercontent.com/4865267/180597277-1a9207d9-00d8-4629-a6b0-a4fde4b5a358.png)


```
type: custom:auto-entities
card:
  type: grid
  columns: 3
  square: false
card_param: cards
filter:
  include:
    - domain: light
      name: stairs_*
      options:
        type: custom:mushroom-light-card
        vertical: true
sort:
  method: state
  reverse: true

```
