### ISSUE TITLE
[Feature]: Actionable Title cards

### ISSUE THREAD

**Issue by galligan** [piitaya/lovelace-mushroom#665]
### Is your feature request related to a problem?

Title cards are a great way to break up an interface, but they could still be actionable with minimal invasive UI to support it.

### Describe the solution you'd like

Apple's Home app app recently made for a big UI change in iOS 16, which now includes sections that even resemble Mushroom!

But one handy thing is that each section (room) gets a title treatment that includes a `>` chevron, where the entire title becomes linkable to that specific room. It would be great if Mushroom's Title card can get the same treatment. It would allow me to build room-specific pages, or have it perform certain other toggle actions if I wanted.

![image](https://user-images.githubusercontent.com/25037981/181358869-fd523e6a-35b1-4cc5-ac46-0470bac6e772.png)

**Comment by estevez-dev** [comment]
I'd love to have such feature as well, but here is an alternative using Mushroom cards and [card-mod](https://github.com/thomasloven/lovelace-card-mod):

![Screenshot 2022-08-16 at 13 07 00](https://user-images.githubusercontent.com/1819786/184854282-9860e1a2-7a3e-49df-8f93-b6819c782c93.png)

Yaml config of title:

```yaml
type: horizontal-stack
cards:
  - type: custom:mushroom-title-card
    title: Вітальня
    alignment: end
  - type: custom:mushroom-chips-card
    chips:
      - type: action
        icon: mdi:chevron-right
        tap_action:
          action: navigate
          navigation_path: living-room
    card_mod:
      style: |-
        .chip-container {
          margin-top: 18px;
        }
```
