### ISSUE TITLE
[Bug]: Template card does not update with entity state

### ISSUE THREAD

**Issue by johannes-z** [piitaya/lovelace-mushroom#690]
### Current Behavior

I have a simple template-card that renders the `last_changed` attribute of an entity. However, the UI does not update accordingly, while it does for an entity-card.

### Expected Behavior

Template-card should also update, when tracked entities/attributes change.

### Steps To Reproduce

Use the following template (change the entity accordingly)

```yaml
- type: custom:mushroom-template-card
  entity: binary_sensor.my_sensor
  secondary: "{{ relative_time(states['binary_sensor.my_sensor'].last_changed) }} ago"
```

### Anything else?

Developer Tools shows:

```
Result type: string
10 minutes ago
This template listens for the following state changed events:

Entity: binary_sensor.my_sensor
```
