### ISSUE TITLE
mushroom-chips-cards unreliable with auto-entities

### ISSUE THREAD

**Issue by mag1024** [piitaya/lovelace-mushroom#698]
### Current Behavior

Greetings fellow mushroom enthusiasts!
I'm not totally sure if this is a mushroom bug, or an auto-entities bug, but the combination has a very frustrating problem that I haven't been able to crack with my rudimentary JS debugging skills.

Occasionally -- depending on the environment, I'd say between 10-50% of the time -- mushroom-chips-cards populated by auto-entities fail to show up in a dashboard. Somehow the card fails to load (remains blank) with no user-visible error. Refreshing the page (sometimes several times) eventually makes it succeed in loading. This happens both on desktop (Chrome on Mac/Windows), and using the HA app (Android).

This does seem to be a mushroom-chips-cards-specific problem, because when I use the regular 'entities' card (with stock, or mushroom-entity-card) populated with the same auto-entities filter, it is completely reliable. I should also note that all of the mushroom-chips-cards/auto-entities on the dashboard seem to be fate-shared -- they either all load, or all fail.

Any thoughts on how to debug this?
Thanks in advance!

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```

### Anything else?

This card works 100% of the time:

```
 - type: custom:auto-entities
    card:
      type: entities
    filter:
      include:
        - state: 'on'
          domain: light
          options:
            type: custom:mushroom-entity-card
        - state: 'on'
          domain: media_player
          options:
            type: custom:mushroom-entity-card
 ```

This configuration is flaky:
```
  - type: custom:auto-entities
    card:
      type: custom:mushroom-chips-card
    card_param: chips
    filter:
      include:
        - state: 'on'
          domain: light
          options:
            type: light
            content_info: name
        - state: 'on'
          domain: media_player
          options:
            type: entity
            content_info: name
            icon: mdi:audio-video
            tap_action:
              action: toggle
  ```
