### ISSUE TITLE
[Feature]: Light Card: Manually Set Icon/Slider color

### ISSUE THREAD

**Issue by Nickno95** [piitaya/lovelace-mushroom#706]
### Is your feature request related to a problem?

There is currently no way to manually override and set the color of the icon and slider in a light entity card. It is either orange or, if the light entity supports color control and use_light_color is true, always has to match the light color.

### Describe the solution you'd like

Add a variable for the light card that allows manually setting the icon and slider colors, like the icon_color variable of the entity card.

**Comment by GitHubGoody** [comment]
+1

**Comment by thiagobruch** [comment]
+1

**Comment by tanishqmanuja** [comment]
+1

**Comment by tantalic** [comment]
+1

**Comment by tanishqmanuja** [comment]
For now we can use something like:
```yaml
type: custom:mushroom-light-card
entity: light.neon_led_strip
icon: mdi:led-strip-variant
...
...
card_mod:
  style: |
    ha-card {
      --rgb-state-light: var(--rgb-pink);
    }

```
