### ISSUE TITLE
[Bug]: Entity ID unknown

### ISSUE THREAD

**Issue by gmcaesar** [piitaya/lovelace-mushroom#730]
### Current Behavior

when using a template chip (not tested elsewhere) "you must specify at least one entity ID" error is given for action despite being defined

### Expected Behavior

tap action to toggle identified input boolean

### Steps To Reproduce

```yaml
type: custom:mushroom-chips-card
chips:
  - type: template
    content: '{{"Michael: "}}{{ states("input_boolean.michael_sleeping")}}'
    icon: mdi:sleep
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data: {}
      target:
        entity_id: input_boolean.michael_sleeping
    entity: input_boolean.michael_sleeping
  - type: template
    content: '{{"Kori: "}}{{ states("input_boolean.kori_sleeping")}}'
    icon: mdi:sleep
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.kori_sleeping
      data: {}
    entity: input_boolean.kori_sleeping
alignment: center
```

### Environment

```markdown
Home Assistant 2022.9.4
Supervisor 2022.08.6
Operating System 9.0
Frontend 20220907.2 - latest
```
