### ISSUE TITLE
[Bug]: Setting icon_color of entity to a CSS variable --primary-color (that is the primary theme color)

### ISSUE THREAD

**Issue by gremo** [piitaya/lovelace-mushroom#754]
### Current Behavior

Setting the `icon_color` to a CSS variable `--primary-color` doesn't work.

```yaml
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: device_tracker.home_pc
    icon: mdi:desktop-classic
    icon_color: --primary-color
    content_info: name
    name: PC

```

### Expected Behavior

Icon color is the value of CSS variable named `--primary-color`

### Environment

```markdown
Home Assistant 2022.9.7
Supervisor 2022.09.3
```

**Comment by piitaya** [comment]
Hello 🙂 CSS variables are not supported for icon color.

**Comment by gremo** [comment]
Oh... so sad to hear that! But thanks for this great addition to Home Assistant! 

Does this will be implemented in the future? Or there is any tech reason behind the difficulty to implement that (shadow roots or anything else)?

**Comment by piitaya** [comment]
A rgb color is needed because we need to add alpha for icon shape and it's not possible yet in CSS with hex color.
You can do this if you want, it should work :
```yaml
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: device_tracker.home_pc
    icon: mdi:desktop-classic
    icon_color: var(--rgb-primary-color)
    content_info: name
    name: PC
```
