### ISSUE TITLE
[Feature]: Ability to change CSS variables "globally"

### ISSUE THREAD

**Issue by gremo** [piitaya/lovelace-mushroom#755]
### Is your feature request related to a problem?

I'm using [card mod](https://github.com/thomasloven/lovelace-card-mod) to change the chip font size for a specific chips group:

```yaml
type: custom:mushroom-chips-card
chips:
  - type: entity
    entity: sensor.casa_interno_esterno_humidity
  - type: entity
    entity: sensor.casa_interno_esterno_battery_percent
alignment: end
card_mod:
  style: |
    ha-card {
      --chip-font-size: 0.4em;
    }
```

It would be fantastic to add the ability to change this globally.

### Describe the solution you'd like

Can globally set `--chip-font-size` CSS variable.
