### ISSUE TITLE
[Bug]: Media card doesn't use the 'source' attribute for it's media info

### ISSUE THREAD

**Issue by JeffersonBledsoe** [piitaya/lovelace-mushroom#758]
### Current Behavior

When settings a media card to read from a TV entity and the 'Use media info' option is set to on, only the default TV icon will show if the integration uses a 'source' attribute to inform Home Assistant what is being played on the device.

### Expected Behavior

When settings a media card to read from a TV entity and the 'Use media info' option is set to on, the icon for the relevant app will be displayed

### Steps To Reproduce

1. Have an entity which uses 'Source' to show what is set on the TV (such as from the webOS integration)
2. Create a 'media' card and enable 'Use media info'

### Environment

```markdown
- OS: HASS OS
- Browser: Chrome/ Safari/ Firefox
- Version: 2.1.3
- Hassio: 2022.9.7
```

### Anything else?

Here's an example of the state from my TV from the webOS (LG) integration:

```yml
source_list:
  - Apple TV
  - Disney+
  - ITV Hub
  - My5
  - NOW
  - Netflix
  - PS5
  - Plex
  - Spotify - Music and Podcasts
  - Twitch
  - UKTV Play
  - YouTube
volume_level: 0.12
is_volume_muted: false
source: PS5
sound_output: tv_speaker
assumed_state: true
device_class: tv
friendly_name: Living Room TV
supported_features: 24509
```
