### ISSUE TITLE
[Bug]: icon_color ignored for conditional entity chips

### ISSUE THREAD

**Issue by ejpenney** [piitaya/lovelace-mushroom#762]
### Current Behavior

This card does not generate a colored chip:

```
  - type: conditional
    conditions:
      - entity: binary_sensor.dog_water
        state_not: 'on'
    chip:
      type: entity
      icon: mdi:water
      entity: binary_sensor.dog_water
      content_info: name
      icon_color: red
      name: Dog Water Low!
```

### Expected Behavior

Should generate a colored chip.  This chip works:

```
  - type: conditional
    conditions:
      - entity: binary_sensor.dog_water
        state_not: "on"
    chip:
      type: template
      entity: binary_sensor.dog_water
      icon: mdi:water
      icon_color: red
      content: Dog Water Low!
```

As does this one (no conditional):

```
  - type: entity
    icon: mdi:water
    entity: binary_sensor.dog_water
    content_info: name
    icon_color: red
    name: Dog Water Low!
```

### Steps To Reproduce

1. Create a Mushroom Chips card
2. Create a conditional chip
3. Fill in condition
4. Add an entity
5. Configure entity to have a colored icon

### Environment

```markdown
- Home Assistant 2022.10.0
- Supervisor 2022.09.1
- Operating System 9.0
- Frontend 20220907.2 - latest
- Mushroom Cards Version: 2.1.3
```

### Anything else?

Pictured here, two conditional chips, one using template, the other with an entity.

![image](https://user-images.githubusercontent.com/21226768/194419128-f4517799-0cee-43e0-bfd0-e317b3b254b1.png)
