### ISSUE TITLE
[Bug]: some confusion about sample case 

### ISSUE THREAD

**Issue by superonions** [piitaya/lovelace-mushroom#781]
### Current Behavior

Thank’s for your awesome lovelace-mushroom

Although this is not a bug, it looks weird
when I browse the sample code in the directory [lovelace-mushroom/.hass_dev/](https://github.com/piitaya/lovelace-mushroom/tree/main/.hass_dev)
```
mode: storage
  dashboards:
    lovelace-mushroom-showcase:
      mode: yaml
      title: Showcase
      icon: mdi:mushroom
      show_in_sidebar: true
      filename: lovelace-mushroom-showcase.yaml
```
you put these codes in the file named **[ui-lovelace.yaml](https://github.com/piitaya/lovelace-mushroom/blob/main/.hass_dev/ui-lovelace.yaml)**, then inculde it in [configuration.yaml](https://github.com/piitaya/lovelace-mushroom/blob/main/.hass_dev/configuration.yaml)
`lovelace: !include ui-lovelace.yaml`

However, in my opinion, ui-lovelace.yaml is a specific file name used for the default dashboard (aka main dashboard), the name should be used for writing lovelace view code rather than the config code. (refer to [dashboards](https://www.home-assistant.io/dashboards/dashboards/) )

when you set  `storage mode` for main dashboard,   "ui-lovelace.yaml" file will no longer be required ,so when you use the same name ui-lovelace.yaml to include config code to configuration.yaml will not cause problems,but this looks weird 

### Environment

```markdown
- OS:
- Node:
- Version:
- Hassio:
```
