### ISSUE TITLE
[Bug]: Template chip icon_color does not support themes

### ISSUE THREAD

**Issue by mechanarchy** [piitaya/lovelace-mushroom#790]
### Current Behavior

Trying to set a template chip to use color `--paper-item-icon-active-color` fails, and the chip has no color. The generated CSS is:
```css
--color:rgb(--paper-item-icon-active-color);
```

This comes from the hard-coded CSS rule here https://github.com/piitaya/lovelace-mushroom/blob/631b1d96b26ebbd42a1bb2167cfd8a4dd913876d/src/cards/chips-card/chips/template-chip.ts#L123

This prevents the chip from following the user-selected frontend theme.

### Expected Behavior

The theme variable color `--paper-item-icon-active-color` is applied. Without support for this, proper themeing of the chip is impossible.

### Steps To Reproduce

```yaml
type: custom:mushroom-chips-card
chips:
  # Hard-coded hex value, which only looks correct with default theme
  - type: template
    icon: mdi:hexagon
    content: hex
    icon_color: '#FDD835'
  # Basic CSS variable, does not work
  - type: template
    icon: mdi:hexagon
    content: bare
    icon_color: '--paper-item-icon-active-color'
  # Specifically saying the value is a 'var', does not work
  - type: template
    icon: mdi:hexagon
    content: var
    icon_color: var(--paper-item-icon-active-color)
  # Mangling the string, produces invalid CSS but correct color result
  - type: template
    icon: mdi:hexagon
    content: malformed
    icon_color: );--color:var(--paper-item-icon-active-color
```

With default dark theme, it looks "ok":
![image](https://user-images.githubusercontent.com/1166756/197904382-92b4a2d5-07a0-4c18-ac03-9fe2bb0a58d7.png)

With noctis theme, it looks incorrect. The correct active color is the blue on the far right:
![image](https://user-images.githubusercontent.com/1166756/197904439-f96840b4-0875-49da-bf4d-80485f1ebfad.png)

### Environment

```markdown
- Version: Mushroom v2.1.3
- Hassio: 2022.10.0
```

**Comment by mechanarchy** [comment]
Just found #754

```yaml
  - type: template
    icon: mdi:hexagon
    content: malformed
    icon_color: );--color:var(--paper-item-icon-active-color
  - type: template
    icon: mdi:hexagon
    content: PC
    icon_color: var(--rgb-primary-color)
```

Suggested solution there does not work for my case, as these are radically different colors (default hass Dark theme):
![image](https://user-images.githubusercontent.com/1166756/197907746-9be1c1e9-6b4a-4f1d-b560-f42b4cfd53a2.png)

Even in Noctis theme, the colors is visually close but not correct:
![image](https://user-images.githubusercontent.com/1166756/197908045-ec241793-9bff-47b0-bec6-820d4f920857.png)

Correct ("malformed" chip / `--paper-item-icon-active-color`): `rgb(26, 137, 245)`
Incorrect ("PC" chip / `--rgb-primary-color`): `rgb(3, 169, 244)`
