### ISSUE TITLE
[Feature]: <title>

### ISSUE THREAD

**Issue by martindybal** [piitaya/lovelace-mushroom#877]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

If I configure cover card like this. It is hard to set the tilt position because the button is not displayed
```yml
type: custom:mushroom-cover-card
name: Window
entity: cover.103_window
show_buttons_control: true
show_position_control: true
show_tilt_position_control: true
```

![image](https://user-images.githubusercontent.com/7644099/204543821-798ba966-3332-4ade-af56-17fa34bc9a8e.png)

### Describe the solution you'd like

Show tilt button next to the position one. 
![image](https://user-images.githubusercontent.com/7644099/204544078-e2b886ad-1681-4379-816f-d4f86ab460f1.png)
