### ISSUE TITLE
Entities card

### ISSUE THREAD

**Issue by pdeelen** [piitaya/lovelace-mushroom#90]
Is it possible to create /change a card thats allowing more than one entity? 
For example to work together with auto-entities card. 

In that way you can create a card filled with entities at a specific state. 

This is how it looks when using a entity-filter card
![image](https://user-images.githubusercontent.com/47855097/153273835-a8158026-7b4b-4388-92dd-e3649c984170.png)

This is how it should look like
![image](https://user-images.githubusercontent.com/47855097/153274047-dab9df3a-634e-4d9c-a3b2-4171d7a8ef7f.png)

**Comment by wilfredsmit** [comment]
Use vertical-stack and horizontal-stack cards, something like this:


```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-entity-card
        entity: light.hanglampen
      - type: custom:mushroom-entity-card
        entity: light.eettafel
      - type: custom:mushroom-entity-card
        entity: light.spotjes
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-entity-card
        entity: light.links
      - type: custom:mushroom-entity-card
        entity: light.rechts
```

**Comment by amitvaria** [comment]
Would a grid-card set to 3 columns work here? It's what I'm doing for my dashboard

**Comment by wilfredsmit** [comment]
Shure, even better I think.

**Comment by pdeelen** [comment]
Hi, thanks for the reply.
But maybe my question was not clear.

This block of code is working with the custom:mushroom-chips-card card. 
But when you try this with the entity card it is not working. 

`type: custom:auto-entities
card:
  type: custom:mushroom-chips-card
card_param: chips
filter:
  include:
    - domain: binary_sensor
      state: 'on'
      attributes:
        device_class: /window|door/
      options:
        type: entity
        content_info: name
  show_empty: true
sort:
  method: state
  reverse: true
`

**Comment by wilfredsmit** [comment]
Could you format your code properly?

**Comment by pdeelen** [comment]
> Could you format your code properly?

Done

**Comment by wilfredsmit** [comment]
> > Could you format your code properly?
> 
> Done

Oké. Now it's clear to me.

I don't know if it's possible right now.

**Comment by piitaya** [comment]
Here's an example : display all sensors as `mushroom-entity-card` and display all lights as `mushroom-entity-card` in a grid layout :

```yaml
type: custom:auto-entities
card:
  type: grid
  columns: 2
  square: false
card_param: cards
filter:
  include:
    - domain: light
      options:
        type: custom:mushroom-light-card
        # You can add all mushroom light card options here 
    - domain: sensor
      options:
        type: custom:mushroom-entity-card
        # You can add all mushroom entity card options here 
```
