### ISSUE TITLE
[Feature]: secondary info on cards should allow templating!

### ISSUE THREAD

**Issue by ahmadnassri** [piitaya/lovelace-mushroom#911]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

not a problem.

### Describe the solution you'd like

cards (such as Lock card) should allow the `secondary_info` property value to be a templated string ... 

example: show the door lock battery level!
 
```yaml
type: custom:mushroom-lock-card
entity: lock.backyard_door
secondary_info: {{ sensor.backyard_door_battery }}
```

**Comment by howardjohn** [comment]
```
- type: custom:mushroom-entity-card
        entity: binary_sensor.garage_door_sensor_ias_zone
        name: Garage
        layout: vertical
      - type: custom:mushroom-template-card
        icon: mdi:garage
        primary: Car
        secondary: >-
          {{ ("Closed" if states[entity].state == "off" else "Open") }} ({{
          states[entity].last_changed|relative_time}})
        layout: vertical
        tap_action:
          action: more-info
        entity: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
        icon_color: '{{ ("" if states[entity].state == "off" else "red") }}'
```

Here is an example of using the entity card and then the same thing with "template card" trying to be exactly the same except with a template in secondary information.

Aside from the complexity there are some correctness issues:
* Logic above doesn't account for "unavailable"; that is my own fault but shows the complexity to get it right
* even if I did account for unavailable, I couldn't properly indicate this - there doesn't seem to be a way to emit the "?" icon that is used in Entity cards when they are unavailable.

So overall IMO templates would still be useful on Entity cards despite having "template card" as an option.
