### ISSUE TITLE
[Bug]: Problems with grouped climates

### ISSUE THREAD

**Issue by cryd-s** [piitaya/lovelace-mushroom#916]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Since a short time me climate group displays all 3 heaters in one card - thats terrible!!

![image](https://user-images.githubusercontent.com/47699362/209778282-1bc6582f-5800-42f8-9faa-358062a1a8bf.png)

### Expected Behavior

in the past they where displayed like:

![image](https://user-images.githubusercontent.com/47699362/209778354-cf248d93-091a-4822-8faa-513c0cb881ff.png)

there should be a option to return this view because i want to control them all at the same time. If i want to control them seperatly i hadnt create a climate group.

### Steps To Reproduce

1. create a climate group via yaml code
2. then add a climate mushroom card 

### Context

YAML state
```type: custom:mushroom-climate-card
entity: climate.wohnzimmer_thermostat
show_temperature_control: true
hvac_modes:
  - 'off'
  - heat
fill_container: false
collapsible_controls: true
tap_action:
  action: toggle
name: Wohnzimmer
layout: horizontal
```

group.yaml:

```
- platform: climate_group
  name: Wohnzimmer Thermostat
  temperature_unit: C # default to celsius, 'C' or 'F'
  entities:
    - climate.lumi_lumi_airrtc_agl001_thermostat_7
    - climate.lumi_lumi_airrtc_agl001_thermostat_8
    - climate.lumi_lumi_airrtc_agl001_thermostat_9
```

### Environment

```markdown
- Browser: Brave
- Home Assistant 2022.12.8
- Supervisor 2022.11.2
- Operating System 9.4
- Frontend 20221213.1 - latest 
- Mushroom: 2.4.1
```

### Anything else?

thanks a lot for the great work
