### ISSUE TITLE
[Bug]: cover card ignores inverted covers

### ISSUE THREAD

**Issue by hartcoded** [piitaya/lovelace-mushroom#921]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I'm using KNX for the window covers, which is open at 0% and closed at 100%. HA itself gives the opportunity to set the cover to inverted, so that the covers work fine. 

The mushroom cover card seems to ignore the inverted state somehow (controls):

It is possible to open/close the covers using the slider by setting an absolute position. So the positioning is okay.

But once the covers are at 0% or at 100% you're not able to use the switches (up and down), because the wrong control gets deactivated (at 0% you can only use the "up" control, but the cover is already totally opened - at 100% you can only use the "down" control, but the cover is already totally closed).

### Expected Behavior

on inverted covers:
at 0%: down control enabled
at 100%: up control enabled

### Context

YAML state
```yaml
cover:
    - name: "rolladen"
      move_long_address: "1/1/13"
      stop_address: "1/3/14"
      position_address: "1/6/13"
      position_state_address: "1/2/13"
      invert_position: true
```

### Environment

```markdown
- Browser: all tested
- HA Version: latest
- Mushroom: latest
```
