### ISSUE TITLE
[Feature]: tap_action to support multiple actions

### ISSUE THREAD

**Issue by and7ey** [piitaya/lovelace-mushroom#930]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Multiple actions to be supported by `tap_action`, for ex.:

```yaml
  - type: action
    icon: mdi:music
    tap_action:
      - action: call-service
        service: light.turn_on
        data:
          effect: Video / Music / Electronic
        target:
          entity_id: light.screen_sync
      - action: call-service
        service: light.turn_on
        data:
          effect: Sound Christmas
        target:
          entity_id: light.sp611e_light
```

**Comment by piitaya** [comment]
Hello 👋
`actions` are not managed by Mushroom. It's a built-in Home Assistant feature. You mush write a script for that and call it from your card. You will be able de add condition, sequences, etc...

**Comment by and7ey** [comment]
Believe, HA natively supports multiple actions:
```
- action
- action
```
but it doesn't work with `tap_action`.

Also HA supports `parallel` actions (see [the doc](https://www.home-assistant.io/docs/scripts/#parallelizing-actions)), but it is not supported by Mushrooms. Am I wrong?

**Comment by piitaya** [comment]
It's supported by scripts and automations, not cards.

**Comment by and7ey** [comment]
Ok, I've expected that it works everywhere.
Thanks for your help.

**Comment by Turton** [comment]
Looks like an attempt was made to implement this, using this structure:

```
tap_action:
  action: multiple
  actions:
    - action: toggle
    - action: navigate
      navigation_path: /lovelace/default_view
```

It looks like it was merged but the work was never completed.  Shame.

[Allow multiple tap/hold/doubletap actions. #8125](https://github.com/home-assistant/frontend/pull/8125)
