### ISSUE TITLE
[Bug]: Name is not shown in Media Card when set for secondary with "Use media info"

### ISSUE THREAD

**Issue by sagilo** [piitaya/lovelace-mushroom#948]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

When setting "name" for `secondary_information` and `Use media info` is enabled, the secondary information setting is overridden and disregarded.  

<img width="353" alt="image" src="https://user-images.githubusercontent.com/5019344/212544789-16feeaba-3f9d-4f79-8353-375392edf65d.png">
 

### Expected Behavior

I'd expect the secondary information to use media info if set to "Default information" and use other value if set manually otherwise, like "name" or "last changed"

### Steps To Reproduce

Play something
Enable "use media info"
Set secondary information to "name" or any value other than "default"

### Context

YAML state
```yaml
type: custom:mushroom-media-player-card
entity: media_player.sonos_one
use_media_info: true
name: One
show_volume_level: true
secondary_info: name

```

### Environment

```markdown
- Browser: chrome
- HA Version: 2023.1.1
- Mushroom: 2.4.1
```
