### ISSUE TITLE
Title Action Call Service

### ISSUE THREAD

**Issue by apivaral** [piitaya/lovelace-mushroom#958]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

Please to Title Actions a Call Service option.

### Describe the solution you'd like

In title actions add Call Service.

**Comment by gatd4** [comment]
also font size and color please

**Comment by piitaya** [comment]
You can already control the font size using themes variables. 
```yaml
mush-title-font-size: 24px
mush-title-font-weight: normal
mush-title-line-height: 1.2
mush-subtitle-font-size: 16px
mush-subtitle-font-weight: normal
mush-subtitle-line-height: 1.2
```

 For color, it uses `primary-text-color` and `secondary-text-color` to keep consistency with home assistant UI.
