### ISSUE TITLE
[Bug]: Select card issus a select just by being displayed

### ISSUE THREAD

**Issue by envy** [piitaya/lovelace-mushroom#974]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have a dashboard which contains a select card. The entity behind that sets the heating mode for all my thermostats via the knx integration like this:

```yaml
-- knx.yml
select:
  - name: "Zentral Heizmodus"
    sync_state: false
    address: 30/2/0
    payload_length: 1
    options:
      - option: "Automatik"
        payload: 0
      - option: "Komfort"
        payload: 1
      - option: "Standby"
        payload: 2
      - option: "Nacht"
        payload: 3
      - option: "Frostschutz"
        payload: 4
```

```yaml
-- dashboard config
type: custom:mushroom-select-card
entity: select.zentral_heizmodus
fill_container: false
layout: horizontal
secondary_info: last-changed
primary_info: name
```

Every time I open that dashboard, the state of the select entity is set again which causes a message going to the KNX bus setting it. 

I also had weird log entries about Home Connect not being able to set my dishwasher mode until I figured out that this was because when editing that dashboard, the card list shows examples and the mushroom select card was displayed with dishwasher mode selection as an example and this also tried to set the mode!

### Expected Behavior

Just display the card, don't set the state.

### Steps To Reproduce

1. Create a select entity in some integration that does something when the state is set
2. Create a select card with that entity
3. Navigate to the dashboard, card will be displayed and the select entity attached to it will be set to the state it already is causing some sideeffect you don't want.

### Context

YAML state
```yaml
options:
  - Automatik
  - Komfort
  - Standby
  - Nacht
  - Frostschutz
icon: mdi:radiator
friendly_name: Zentral Heizmodus
```

### Environment

```markdown
- Browser: Firefox 109.0 on Windows 10
- HA Version: 2023.01.6
- Mushroom: 2.5.2
```
