### ISSUE TITLE
[Bug]: Select Card causes service call on render!

### ISSUE THREAD

**Issue by kulmegil** [piitaya/lovelace-mushroom#983]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

It appears that whenever Mushroom Select Card is rendering it's causing service call (`select.select_option`) on it's entity.

I have a select entity that controls foreground app on my Android TV.
It will also power on TV using magic packet (Wake on LAN) if it's off,
allowing to quickly start media playback.

Problem:
Whenever my dashboard with Mushroom Select Card is rendering it causes my TV to turn on automatically!

To add to the insult my HA has decided to populate Mushroom card with this particular entity in "ADD CARD" dialog, causing the TV to turn on whenever I add a new card as well!

ps It appears that `select.select_option` will try to execute actions chain even when option is already marked as selected.

### Expected Behavior

No any service calls should be made when card is rendering.
Only user interacting can cause service call.
This is how standard select combo box as entities row behave.

### Steps To Reproduce

1. Add Mushroom Select Card 
2. Reload page

### Context

Card:
```yaml
type: custom:mushroom-select-card
entity: select.light_control_combo
```
Where `select.light_control_combo` can be e.g.:
```yaml
template:
  - select:
      - name:            Light control combo
        state:           'on'
        options:         '{{ ["on", "off"] }}'
        select_option:
          - service:     '{{ "homeassistant.turn_on" if option == "on" else "homeassistant.turn_off" }}'
            target:
              entity_id: light.any_light_entity
```

### Environment

```markdown
- Browser: Firefox 109.0, Chrome 109.0, Android Companion App 2023.1
- HA Version: 2023.1.7
- Mushroom: 2.5.2
```
